# The following variable is specific to this backend and its correct
# values might depend on your environment - feel free to set it accordingly.

ORACLEINCLUDEDIR = -I/usr/lib/oracle/xe/app/oracle/product/10.2.0/server/rdbms/public 
ORACLELIBDIR = -L/usr/lib/oracle/xe/app/oracle/product/10.2.0/server/lib 
ORACLELIBS = -lclntsh -lnnz10

# The rest of the Makefile is indepentent of the target environment.

COMPILER = g++
CXXFLAGS = -Wall -pedantic -Wno-long-long
INCLUDEDIRS = -I.. -I../../../core -I../../../core/test ${ORACLEINCLUDEDIR}
LIBDIRS = -L.. -L../../../core ${ORACLELIBDIR}
LIBS = -lsoci_core -lsoci_oracle -ldl -lboost_date_time ${ORACLELIBS}


test-oracle : test-oracle.cpp 
#../../../core/test/common-tests.h
	${COMPILER} -o $@ $? ${CXXFLAGS} ${INCLUDEDIRS} ${LIBDIRS} ${LIBS}


clean :
	rm -f *.o test-oracle
