name: Install-dependencies

inputs:
  build_dir:
    description: 'The directory where to build.'
    required: true
    type: string
  build_type:
    description: 'The build type to use.'
    required: true
    type: string
  conan_remote_name:
    description: 'The name of the Conan remote to use.'
    required: true
    type: string

# Install the Conan profiles and log into the specified remote. We first remove
# the remote if it already exists, which can occur on self-hosted runners where
# the workspace is not cleaned up between runs.
runs:
  using: composite
  steps:
    - name: Install Conan dependencies
      shell: bash
      run: |
        mkdir -p ${{ inputs.build_dir }}
        cd ${{ inputs.build_dir }}
        conan install \
          --output-folder . \
          --build '*' \
          --options:host "&:tests=True" \
          --options:host "&:xrpld=True" \
          --settings:all build_type=${{ inputs.build_type }} \
          ..
    - name: Upload Conan dependencies
      shell: bash
      run: conan upload '*' --confirm --check --force --remote ${{ inputs.conan_remote_name }}
