// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: org/xrpl/rpc/v1/get_ledger_entry.proto
// Protobuf C++ Version: 6.33.5

#include "org/xrpl/rpc/v1/get_ledger_entry.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace org {
namespace xrpl {
namespace rpc {
namespace v1 {

inline constexpr GetLedgerEntryResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        ledger_object_{nullptr},
        ledger_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR GetLedgerEntryResponse::GetLedgerEntryResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GetLedgerEntryResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetLedgerEntryResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetLedgerEntryResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetLedgerEntryResponseDefaultTypeInternal() {}
  union {
    GetLedgerEntryResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetLedgerEntryResponseDefaultTypeInternal _GetLedgerEntryResponse_default_instance_;

inline constexpr GetLedgerEntryRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        client_ip_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ledger_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR GetLedgerEntryRequest::GetLedgerEntryRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GetLedgerEntryRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetLedgerEntryRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetLedgerEntryRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetLedgerEntryRequestDefaultTypeInternal() {}
  union {
    GetLedgerEntryRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetLedgerEntryRequestDefaultTypeInternal _GetLedgerEntryRequest_default_instance_;
}  // namespace v1
}  // namespace rpc
}  // namespace xrpl
}  // namespace org
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto = nullptr;
const ::uint32_t
    TableStruct_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerEntryRequest, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerEntryRequest, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerEntryRequest, _impl_.ledger_),
        PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerEntryRequest, _impl_.client_ip_),
        0,
        2,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerEntryResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerEntryResponse, _impl_.ledger_object_),
        PROTOBUF_FIELD_OFFSET(::org::xrpl::rpc::v1::GetLedgerEntryResponse, _impl_.ledger_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::org::xrpl::rpc::v1::GetLedgerEntryRequest)},
        {9, sizeof(::org::xrpl::rpc::v1::GetLedgerEntryResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::org::xrpl::rpc::v1::_GetLedgerEntryRequest_default_instance_._instance,
    &::org::xrpl::rpc::v1::_GetLedgerEntryResponse_default_instance_._instance,
};
const char descriptor_table_protodef_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n&org/xrpl/rpc/v1/get_ledger_entry.proto"
    "\022\017org.xrpl.rpc.v1\032\034org/xrpl/rpc/v1/ledge"
    "r.proto\"i\n\025GetLedgerEntryRequest\022\013\n\003key\030"
    "\001 \001(\014\0220\n\006ledger\030\002 \001(\0132 .org.xrpl.rpc.v1."
    "LedgerSpecifier\022\021\n\tclient_ip\030\003 \001(\t\"\203\001\n\026G"
    "etLedgerEntryResponse\0227\n\rledger_object\030\001"
    " \001(\0132 .org.xrpl.rpc.v1.RawLedgerObject\0220"
    "\n\006ledger\030\002 \001(\0132 .org.xrpl.rpc.v1.LedgerS"
    "pecifierB\023\n\017org.xrpl.rpc.v1P\001b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto_deps[1] = {
        &::descriptor_table_org_2fxrpl_2frpc_2fv1_2fledger_2eproto,
};
static ::absl::once_flag descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto = {
    false,
    false,
    357,
    descriptor_table_protodef_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto,
    "org/xrpl/rpc/v1/get_ledger_entry.proto",
    &descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto_once,
    descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto_deps,
    1,
    2,
    schemas,
    file_default_instances,
    TableStruct_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto::offsets,
    file_level_enum_descriptors_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto,
    file_level_service_descriptors_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto,
};
namespace org {
namespace xrpl {
namespace rpc {
namespace v1 {
// ===================================================================

class GetLedgerEntryRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GetLedgerEntryRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GetLedgerEntryRequest, _impl_._has_bits_);
};

void GetLedgerEntryRequest::clear_ledger() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ledger_ != nullptr) _impl_.ledger_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
GetLedgerEntryRequest::GetLedgerEntryRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetLedgerEntryRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:org.xrpl.rpc.v1.GetLedgerEntryRequest)
}
PROTOBUF_NDEBUG_INLINE GetLedgerEntryRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::org::xrpl::rpc::v1::GetLedgerEntryRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        key_(arena, from.key_),
        client_ip_(arena, from.client_ip_) {}

GetLedgerEntryRequest::GetLedgerEntryRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GetLedgerEntryRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetLedgerEntryRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetLedgerEntryRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.ledger_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ledger_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:org.xrpl.rpc.v1.GetLedgerEntryRequest)
}
PROTOBUF_NDEBUG_INLINE GetLedgerEntryRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        key_(arena),
        client_ip_(arena) {}

inline void GetLedgerEntryRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ledger_ = {};
}
GetLedgerEntryRequest::~GetLedgerEntryRequest() {
  // @@protoc_insertion_point(destructor:org.xrpl.rpc.v1.GetLedgerEntryRequest)
  SharedDtor(*this);
}
inline void GetLedgerEntryRequest::SharedDtor(MessageLite& self) {
  GetLedgerEntryRequest& this_ = static_cast<GetLedgerEntryRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.key_.Destroy();
  this_._impl_.client_ip_.Destroy();
  delete this_._impl_.ledger_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GetLedgerEntryRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GetLedgerEntryRequest(arena);
}
constexpr auto GetLedgerEntryRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GetLedgerEntryRequest),
                                            alignof(GetLedgerEntryRequest));
}
constexpr auto GetLedgerEntryRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GetLedgerEntryRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GetLedgerEntryRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GetLedgerEntryRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GetLedgerEntryRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GetLedgerEntryRequest>(), &GetLedgerEntryRequest::ByteSizeLong,
              &GetLedgerEntryRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GetLedgerEntryRequest, _impl_._cached_size_),
          false,
      },
      &GetLedgerEntryRequest::kDescriptorMethods,
      &descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GetLedgerEntryRequest_class_data_ =
        GetLedgerEntryRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GetLedgerEntryRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GetLedgerEntryRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GetLedgerEntryRequest_class_data_.tc_table);
  return GetLedgerEntryRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 55, 2>
GetLedgerEntryRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GetLedgerEntryRequest, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    GetLedgerEntryRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::org::xrpl::rpc::v1::GetLedgerEntryRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bytes key = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(GetLedgerEntryRequest, _impl_.key_)}},
    // .org.xrpl.rpc.v1.LedgerSpecifier ledger = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 2, 0,
      PROTOBUF_FIELD_OFFSET(GetLedgerEntryRequest, _impl_.ledger_)}},
    // string client_ip = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0,
      PROTOBUF_FIELD_OFFSET(GetLedgerEntryRequest, _impl_.client_ip_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes key = 1;
    {PROTOBUF_FIELD_OFFSET(GetLedgerEntryRequest, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // .org.xrpl.rpc.v1.LedgerSpecifier ledger = 2;
    {PROTOBUF_FIELD_OFFSET(GetLedgerEntryRequest, _impl_.ledger_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string client_ip = 3;
    {PROTOBUF_FIELD_OFFSET(GetLedgerEntryRequest, _impl_.client_ip_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::org::xrpl::rpc::v1::LedgerSpecifier>()},
  }},
  {{
    "\45\0\0\11\0\0\0\0"
    "org.xrpl.rpc.v1.GetLedgerEntryRequest"
    "client_ip"
  }},
};
PROTOBUF_NOINLINE void GetLedgerEntryRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:org.xrpl.rpc.v1.GetLedgerEntryRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.key_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.client_ip_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.ledger_ != nullptr);
      _impl_.ledger_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GetLedgerEntryRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GetLedgerEntryRequest& this_ = static_cast<const GetLedgerEntryRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GetLedgerEntryRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GetLedgerEntryRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:org.xrpl.rpc.v1.GetLedgerEntryRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes key = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_key().empty()) {
      const ::std::string& _s = this_._internal_key();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  // .org.xrpl.rpc.v1.LedgerSpecifier ledger = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.ledger_, this_._impl_.ledger_->GetCachedSize(), target,
        stream);
  }

  // string client_ip = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_client_ip().empty()) {
      const ::std::string& _s = this_._internal_client_ip();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "org.xrpl.rpc.v1.GetLedgerEntryRequest.client_ip");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:org.xrpl.rpc.v1.GetLedgerEntryRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GetLedgerEntryRequest::ByteSizeLong(const MessageLite& base) {
  const GetLedgerEntryRequest& this_ = static_cast<const GetLedgerEntryRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GetLedgerEntryRequest::ByteSizeLong() const {
  const GetLedgerEntryRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:org.xrpl.rpc.v1.GetLedgerEntryRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // bytes key = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_key().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_key());
      }
    }
    // string client_ip = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_client_ip().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_client_ip());
      }
    }
    // .org.xrpl.rpc.v1.LedgerSpecifier ledger = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.ledger_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GetLedgerEntryRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<GetLedgerEntryRequest*>(&to_msg);
  auto& from = static_cast<const GetLedgerEntryRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:org.xrpl.rpc.v1.GetLedgerEntryRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_key().empty()) {
        _this->_internal_set_key(from._internal_key());
      } else {
        if (_this->_impl_.key_.IsDefault()) {
          _this->_internal_set_key("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_client_ip().empty()) {
        _this->_internal_set_client_ip(from._internal_client_ip());
      } else {
        if (_this->_impl_.client_ip_.IsDefault()) {
          _this->_internal_set_client_ip("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.ledger_ != nullptr);
      if (_this->_impl_.ledger_ == nullptr) {
        _this->_impl_.ledger_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ledger_);
      } else {
        _this->_impl_.ledger_->MergeFrom(*from._impl_.ledger_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void GetLedgerEntryRequest::CopyFrom(const GetLedgerEntryRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:org.xrpl.rpc.v1.GetLedgerEntryRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetLedgerEntryRequest::InternalSwap(GetLedgerEntryRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.client_ip_, &other->_impl_.client_ip_, arena);
  swap(_impl_.ledger_, other->_impl_.ledger_);
}

::google::protobuf::Metadata GetLedgerEntryRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetLedgerEntryResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GetLedgerEntryResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GetLedgerEntryResponse, _impl_._has_bits_);
};

void GetLedgerEntryResponse::clear_ledger_object() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ledger_object_ != nullptr) _impl_.ledger_object_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
void GetLedgerEntryResponse::clear_ledger() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ledger_ != nullptr) _impl_.ledger_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
GetLedgerEntryResponse::GetLedgerEntryResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetLedgerEntryResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:org.xrpl.rpc.v1.GetLedgerEntryResponse)
}
PROTOBUF_NDEBUG_INLINE GetLedgerEntryResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::org::xrpl::rpc::v1::GetLedgerEntryResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

GetLedgerEntryResponse::GetLedgerEntryResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GetLedgerEntryResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetLedgerEntryResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetLedgerEntryResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.ledger_object_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ledger_object_)
                : nullptr;
  _impl_.ledger_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ledger_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:org.xrpl.rpc.v1.GetLedgerEntryResponse)
}
PROTOBUF_NDEBUG_INLINE GetLedgerEntryResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void GetLedgerEntryResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, ledger_object_),
           0,
           offsetof(Impl_, ledger_) -
               offsetof(Impl_, ledger_object_) +
               sizeof(Impl_::ledger_));
}
GetLedgerEntryResponse::~GetLedgerEntryResponse() {
  // @@protoc_insertion_point(destructor:org.xrpl.rpc.v1.GetLedgerEntryResponse)
  SharedDtor(*this);
}
inline void GetLedgerEntryResponse::SharedDtor(MessageLite& self) {
  GetLedgerEntryResponse& this_ = static_cast<GetLedgerEntryResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.ledger_object_;
  delete this_._impl_.ledger_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GetLedgerEntryResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GetLedgerEntryResponse(arena);
}
constexpr auto GetLedgerEntryResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GetLedgerEntryResponse),
                                            alignof(GetLedgerEntryResponse));
}
constexpr auto GetLedgerEntryResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GetLedgerEntryResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GetLedgerEntryResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GetLedgerEntryResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GetLedgerEntryResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GetLedgerEntryResponse>(), &GetLedgerEntryResponse::ByteSizeLong,
              &GetLedgerEntryResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GetLedgerEntryResponse, _impl_._cached_size_),
          false,
      },
      &GetLedgerEntryResponse::kDescriptorMethods,
      &descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GetLedgerEntryResponse_class_data_ =
        GetLedgerEntryResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GetLedgerEntryResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GetLedgerEntryResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GetLedgerEntryResponse_class_data_.tc_table);
  return GetLedgerEntryResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2>
GetLedgerEntryResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GetLedgerEntryResponse, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    GetLedgerEntryResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::org::xrpl::rpc::v1::GetLedgerEntryResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .org.xrpl.rpc.v1.LedgerSpecifier ledger = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1,
      PROTOBUF_FIELD_OFFSET(GetLedgerEntryResponse, _impl_.ledger_)}},
    // .org.xrpl.rpc.v1.RawLedgerObject ledger_object = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(GetLedgerEntryResponse, _impl_.ledger_object_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .org.xrpl.rpc.v1.RawLedgerObject ledger_object = 1;
    {PROTOBUF_FIELD_OFFSET(GetLedgerEntryResponse, _impl_.ledger_object_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .org.xrpl.rpc.v1.LedgerSpecifier ledger = 2;
    {PROTOBUF_FIELD_OFFSET(GetLedgerEntryResponse, _impl_.ledger_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::org::xrpl::rpc::v1::RawLedgerObject>()},
      {::_pbi::TcParser::GetTable<::org::xrpl::rpc::v1::LedgerSpecifier>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void GetLedgerEntryResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:org.xrpl.rpc.v1.GetLedgerEntryResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(_impl_.ledger_object_ != nullptr);
      _impl_.ledger_object_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.ledger_ != nullptr);
      _impl_.ledger_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GetLedgerEntryResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GetLedgerEntryResponse& this_ = static_cast<const GetLedgerEntryResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GetLedgerEntryResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GetLedgerEntryResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:org.xrpl.rpc.v1.GetLedgerEntryResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .org.xrpl.rpc.v1.RawLedgerObject ledger_object = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, *this_._impl_.ledger_object_, this_._impl_.ledger_object_->GetCachedSize(), target,
        stream);
  }

  // .org.xrpl.rpc.v1.LedgerSpecifier ledger = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.ledger_, this_._impl_.ledger_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:org.xrpl.rpc.v1.GetLedgerEntryResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GetLedgerEntryResponse::ByteSizeLong(const MessageLite& base) {
  const GetLedgerEntryResponse& this_ = static_cast<const GetLedgerEntryResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GetLedgerEntryResponse::ByteSizeLong() const {
  const GetLedgerEntryResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:org.xrpl.rpc.v1.GetLedgerEntryResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // .org.xrpl.rpc.v1.RawLedgerObject ledger_object = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.ledger_object_);
    }
    // .org.xrpl.rpc.v1.LedgerSpecifier ledger = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.ledger_);
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GetLedgerEntryResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<GetLedgerEntryResponse*>(&to_msg);
  auto& from = static_cast<const GetLedgerEntryResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:org.xrpl.rpc.v1.GetLedgerEntryResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.ledger_object_ != nullptr);
      if (_this->_impl_.ledger_object_ == nullptr) {
        _this->_impl_.ledger_object_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ledger_object_);
      } else {
        _this->_impl_.ledger_object_->MergeFrom(*from._impl_.ledger_object_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.ledger_ != nullptr);
      if (_this->_impl_.ledger_ == nullptr) {
        _this->_impl_.ledger_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.ledger_);
      } else {
        _this->_impl_.ledger_->MergeFrom(*from._impl_.ledger_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void GetLedgerEntryResponse::CopyFrom(const GetLedgerEntryResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:org.xrpl.rpc.v1.GetLedgerEntryResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetLedgerEntryResponse::InternalSwap(GetLedgerEntryResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetLedgerEntryResponse, _impl_.ledger_)
      + sizeof(GetLedgerEntryResponse::_impl_.ledger_)
      - PROTOBUF_FIELD_OFFSET(GetLedgerEntryResponse, _impl_.ledger_object_)>(
          reinterpret_cast<char*>(&_impl_.ledger_object_),
          reinterpret_cast<char*>(&other->_impl_.ledger_object_));
}

::google::protobuf::Metadata GetLedgerEntryResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace rpc
}  // namespace xrpl
}  // namespace org
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_org_2fxrpl_2frpc_2fv1_2fget_5fledger_5fentry_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
