# The following variable is specific to this backend and its correct
# values might depend on your environment - feel free to set it accordingly.

FIREBIRDINCLUDEDIR = -I/usr/local/firebird/include 
FIREBIRDLIBDIR = -L/usr/local/firebird/lib 
FIREBIRDLIBS = -lfbclient -lpthread

# The rest of the Makefile is indepentent of the target environment.

COMPILER = g++
CXXFLAGS = -Wall -pedantic -Wno-long-long
INCLUDEDIRS = -I.. -I../../../core ${FIREBIRDINCLUDEDIR}
LIBDIRS = -L.. -L../../../core ${FIREBIRDLIBDIR}
LIBS = -lsoci_core -lsoci_firebird -ldl ${FIREBIRDLIBS}


test-firebird : test-firebird.cpp
	${COMPILER} -o $@ $? ${CXXFLAGS} ${INCLUDEDIRS} ${LIBDIRS} ${LIBS}


clean :
	rm -f *.o test-firebird
