#!/usr/bin/env bash
#
# ini2toml.sh - Convert xrpld INI configuration files to TOML format
#
# Usage: ./ini2toml.sh input.cfg [output.toml]
#        If output.toml is not specified, outputs to stdout
#
# Conversion rules:
#   - Root-level key=value pairs are preserved as-is
#   - Sections with only standalone items become top-level key=value or arrays
#   - Sections listed under [server] become [server.ports.<name>]
#   - All other sections with key=value pairs become [section] tables

set -e

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 input.cfg [output.toml]" >&2
    echo "       Converts xrpld INI config to TOML format." >&2
    exit 1
fi

INPUT_FILE="$1"
OUTPUT_FILE="${2:-/dev/stdout}"

if [[ ! -f "$INPUT_FILE" ]]; then
    echo "Error: Input file '$INPUT_FILE' not found." >&2
    exit 1
fi

# Create temp files for storing parsed data (Bash 3.2 compatible - no associative arrays)
TMPDIR="${TMPDIR:-/tmp}"
ROOT_KEYS_FILE=$(mktemp "${TMPDIR}/ini2toml_root_keys.XXXXXX")
ROOT_ITEMS_FILE=$(mktemp "${TMPDIR}/ini2toml_root_items.XXXXXX")
SECTIONS_FILE=$(mktemp "${TMPDIR}/ini2toml_sections.XXXXXX")
SECTION_ORDER_FILE=$(mktemp "${TMPDIR}/ini2toml_section_order.XXXXXX")
SERVER_PORTS_FILE=""

cleanup() {
    rm -f "$ROOT_KEYS_FILE" "$ROOT_ITEMS_FILE" "$SECTIONS_FILE" "$SECTION_ORDER_FILE" "$SERVER_PORTS_FILE"
}
trap cleanup EXIT

# Trim leading and trailing whitespace
trim() {
    echo "$1" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}

# Format a value for TOML output (quote strings, preserve numbers/booleans)
format_value() {
    local value
    value="$(trim "$1")"

    if [[ "$value" =~ ^-?[0-9]+$ ]]; then
        echo "$value"
    elif [[ "$value" =~ ^-?[0-9]+\.[0-9]+$ ]]; then
        echo "$value"
    elif [[ "$value" =~ ^(true|false)$ ]]; then
        echo "$value"
    else
        value="${value//\\/\\\\}"
        value="${value//\"/\\\"}"
        echo "\"$value\""
    fi
}

current_section=""

# First pass: parse the INI file
while IFS= read -r line || [[ -n "$line" ]]; do
    # Trim trailing whitespace
    line="${line%"${line##*[![:space:]]}"}"

    # Skip empty lines and comments
    [[ -z "$line" ]] && continue
    [[ "$line" =~ ^[[:space:]]*# ]] && continue

    # Section header: [section_name]
    if [[ "$line" =~ ^\[([^\]]+)\]$ ]]; then
        current_section="${BASH_REMATCH[1]}"
        if ! grep -qxF "$current_section" "$SECTION_ORDER_FILE" 2>/dev/null; then
            echo "$current_section" >> "$SECTION_ORDER_FILE"
        fi
        continue
    fi

    # Key=value pair
    if [[ "$line" =~ ^([^=]+)=(.*)$ ]]; then
        key="$(trim "${BASH_REMATCH[1]}")"
        value="${BASH_REMATCH[2]}"
        if [[ -z "$current_section" ]]; then
            echo "${key}=${value}" >> "$ROOT_KEYS_FILE"
        else
            echo "${current_section}|KV|${key}=${value}" >> "$SECTIONS_FILE"
        fi
        continue
    fi

    # Standalone value (e.g., port names under [server], validator keys)
    value="$(trim "$line")"
    if [[ -n "$value" ]]; then
        if [[ -z "$current_section" ]]; then
            echo "$value" >> "$ROOT_ITEMS_FILE"
        else
            echo "${current_section}|ITEM|${value}" >> "$SECTIONS_FILE"
        fi
    fi
done < "$INPUT_FILE"

# Second pass: output TOML
{
    echo "# Converted from $INPUT_FILE"
    echo "# Generated by ini2toml.sh on $(date)"
    echo ""

    # Output root-level keys first (required by TOML)
    if [[ -f "$ROOT_KEYS_FILE" ]]; then
        while IFS= read -r kv_line; do
            if [[ "$kv_line" =~ ^([^=]+)=(.*)$ ]]; then
                key="${BASH_REMATCH[1]}"
                value="${BASH_REMATCH[2]}"
                formatted_value=$(format_value "$value")
                echo "${key} = ${formatted_value}"
            fi
        done < "$ROOT_KEYS_FILE"
    fi

    # Output root-level standalone items as an array if any
    if [[ -s "$ROOT_ITEMS_FILE" ]]; then
        echo ""
        echo "# Root-level items (may need manual review)"
        echo "items = ["
        while IFS= read -r item; do
            formatted_value=$(format_value "$item")
            echo "    ${formatted_value},"
        done < "$ROOT_ITEMS_FILE"
        echo "]"
    fi

    # Collect server port names (items listed under [server] section)
    # These sections will be output as [server.ports.<name>]
    SERVER_PORTS_FILE=$(mktemp "${TMPDIR}/ini2toml_server_ports.XXXXXX")
    grep "^server|ITEM|" "$SECTIONS_FILE" 2>/dev/null | cut -d'|' -f3 > "$SERVER_PORTS_FILE" || true

    # FIRST PASS: Output sections that become top-level key-value pairs
    # (sections with only standalone items, not [server], and not server ports)
    if [[ -f "$SECTION_ORDER_FILE" ]]; then
        while IFS= read -r section; do
            [[ -z "$section" ]] && continue
            # Skip server section
            [[ "$section" == "server" ]] && continue
            # Skip server ports (they become [server.ports.*])
            grep -qxF "$section" "$SERVER_PORTS_FILE" 2>/dev/null && continue
            # Skip sections that have key=value pairs (they need [section] headers)
            grep -q "^${section}|KV|" "$SECTIONS_FILE" 2>/dev/null && continue

            # Only process sections with standalone items only
            if grep -q "^${section}|ITEM|" "$SECTIONS_FILE" 2>/dev/null; then
                item_count=$(grep -c "^${section}|ITEM|" "$SECTIONS_FILE")
                if [[ "$item_count" -eq 1 ]]; then
                    # Single item becomes a simple key-value pair
                    item=$(grep "^${section}|ITEM|" "$SECTIONS_FILE" | head -1 | cut -d'|' -f3)
                    formatted_value=$(format_value "$item")
                    echo "${section} = ${formatted_value}"
                else
                    # Multiple items become an array
                    echo "${section} = ["
                    grep "^${section}|ITEM|" "$SECTIONS_FILE" | while IFS='|' read -r _ _ item; do
                        formatted_value=$(format_value "$item")
                        echo "    ${formatted_value},"
                    done
                    echo "]"
                fi
            fi
        done < "$SECTION_ORDER_FILE"
    fi

    # SECOND PASS: Output sections with [section] headers
    if [[ -f "$SECTION_ORDER_FILE" ]]; then
        while IFS= read -r section; do
            [[ -z "$section" ]] && continue

            # Check if this section is a server port (listed under [server])
            is_server_port=false
            if grep -qxF "$section" "$SERVER_PORTS_FILE" 2>/dev/null; then
                is_server_port=true
            fi

            # Skip [server] section (its items are port references)
            [[ "$section" == "server" ]] && continue

            # Skip sections that only have items and no KV pairs (already output above)
            # unless they're server ports
            if ! $is_server_port; then
                if grep -q "^${section}|ITEM|" "$SECTIONS_FILE" 2>/dev/null; then
                    if ! grep -q "^${section}|KV|" "$SECTIONS_FILE" 2>/dev/null; then
                        continue
                    fi
                fi
            fi

            # Output section with key=value pairs as [section]
            if grep -q "^${section}|KV|" "$SECTIONS_FILE" 2>/dev/null; then
                echo ""
                # Sections listed under [server] become [server.ports.section_name]
                if $is_server_port; then
                    echo "[server.ports.${section}]"
                else
                    echo "[$section]"
                fi
                grep "^${section}|KV|" "$SECTIONS_FILE" | while IFS='|' read -r _ _ kv_line; do
                    if [[ "$kv_line" =~ ^([^=]+)=(.*)$ ]]; then
                        key="${BASH_REMATCH[1]}"
                        value="${BASH_REMATCH[2]}"
                        formatted_value=$(format_value "$value")
                        echo "${key} = ${formatted_value}"
                    fi
                done
            fi
        done < "$SECTION_ORDER_FILE"
    fi

} > "$OUTPUT_FILE"

if [[ "$OUTPUT_FILE" != "/dev/stdout" ]]; then
    echo "Converted '$INPUT_FILE' to '$OUTPUT_FILE'"
fi
