#!/usr/bin/env bash
#
# ini2toml.sh - Convert xrpld INI configuration files to TOML format
#
# Usage: ./ini2toml.sh input.cfg [output.toml]
#        If output.toml is not specified, outputs to stdout

set -e

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 input.cfg [output.toml]" >&2
    echo "       Converts xrpld INI config to TOML format, preserving comments." >&2
    exit 1
fi

INPUT_FILE="$1"
OUTPUT_FILE="${2:-/dev/stdout}"

if [[ ! -f "$INPUT_FILE" ]]; then
    echo "Error: Input file '$INPUT_FILE' not found." >&2
    exit 1
fi

# State variables
current_section=""
in_section=false
pending_comments=()

# Function to output pending comments
flush_comments() {
    for comment in "${pending_comments[@]}"; do
        echo "$comment"
    done
    pending_comments=()
}

# Function to determine if a value needs quoting in TOML
format_value() {
    local value="$1"
    # Remove leading/trailing whitespace
    value="$(echo "$value" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"

    # Check if it's a pure integer
    if [[ "$value" =~ ^-?[0-9]+$ ]]; then
        echo "$value"
    # Check if it's a float
    elif [[ "$value" =~ ^-?[0-9]+\.[0-9]+$ ]]; then
        echo "$value"
    # Check for boolean-like values
    elif [[ "$value" =~ ^(true|false)$ ]]; then
        echo "$value"
    # Otherwise quote it as a string
    else
        # Escape backslashes and quotes for TOML
        value="${value//\\/\\\\}"
        value="${value//\"/\\\"}"
        echo "\"$value\""
    fi
}

# Process the file
{
    echo "# Converted from $INPUT_FILE"
    echo "# Generated by ini2toml.sh on $(date)"
    echo ""

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Trim trailing whitespace but preserve leading
        line="${line%"${line##*[![:space:]]}"}"

        # Empty line
        if [[ -z "$line" ]]; then
            flush_comments
            echo ""
            continue
        fi

        # Comment line (starts with # after optional whitespace)
        if [[ "$line" =~ ^[[:space:]]*# ]]; then
            # Store comment for later output
            pending_comments+=("$line")
            continue
        fi

        # Section header [section_name]
        if [[ "$line" =~ ^\[([^\]]+)\]$ ]]; then
            flush_comments
            current_section="${BASH_REMATCH[1]}"
            in_section=true
            echo "[$current_section]"
            continue
        fi

        # Key=value pair
        if [[ "$line" =~ ^([^=]+)=(.*)$ ]]; then
            flush_comments
            key="${BASH_REMATCH[1]}"
            value="${BASH_REMATCH[2]}"
            # Trim whitespace from key
            key="$(echo "$key" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
            formatted_value=$(format_value "$value")
            echo "${key} = ${formatted_value}"
            continue
        fi

        # Standalone value (like port names in [server] section or list items)
        if $in_section; then
            flush_comments
            # Trim whitespace
            value="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
            if [[ -n "$value" ]]; then
                # For standalone values, output as array element comment
                # (TOML doesn't support bare values in sections like INI does)
                # These need manual conversion to arrays
                echo "# MANUAL: Convert to array element: $value"
            fi
        fi

    done < "$INPUT_FILE"

    # Flush any remaining comments
    flush_comments

} > "$OUTPUT_FILE"

if [[ "$OUTPUT_FILE" != "/dev/stdout" ]]; then
    echo "Converted '$INPUT_FILE' to '$OUTPUT_FILE'"
    echo "NOTE: Review the output for any '# MANUAL:' comments that need attention."
fi
