#!/usr/bin/env bash
#
# ini2yaml.sh - Convert xrpld INI configuration files to YAML format
#
# Usage: ./ini2yaml.sh input.cfg [output.yaml]
#        If output.yaml is not specified, outputs to stdout

set -e

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 input.cfg [output.yaml]" >&2
    echo "       Converts xrpld INI config to YAML format, preserving comments." >&2
    exit 1
fi

INPUT_FILE="$1"
OUTPUT_FILE="${2:-/dev/stdout}"

if [[ ! -f "$INPUT_FILE" ]]; then
    echo "Error: Input file '$INPUT_FILE' not found." >&2
    exit 1
fi

# State variables
current_section=""
in_section=false
pending_comments=()

# Function to output pending comments with proper indentation
flush_comments() {
    local indent="$1"
    for comment in "${pending_comments[@]}"; do
        echo "${indent}${comment}"
    done
    pending_comments=()
}

# Function to determine if a value looks like a number or boolean
format_value() {
    local value="$1"
    # Remove leading/trailing whitespace
    value="$(echo "$value" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"

    # Check if it's a pure integer
    if [[ "$value" =~ ^-?[0-9]+$ ]]; then
        echo "$value"
    # Check if it's a float
    elif [[ "$value" =~ ^-?[0-9]+\.[0-9]+$ ]]; then
        echo "$value"
    # Check for boolean-like values
    elif [[ "$value" =~ ^(true|false|yes|no|on|off)$ ]]; then
        echo "$value"
    # Otherwise quote it as a string
    else
        # Escape any existing quotes and wrap in quotes if it contains special chars
        if [[ "$value" =~ [\:\#\[\]\{\}\,\&\*\!\|\>\<\%\@\`] ]] || [[ "$value" =~ ^[[:space:]] ]] || [[ "$value" =~ [[:space:]]$ ]]; then
            echo "\"$value\""
        else
            echo "$value"
        fi
    fi
}

# Process the file
{
    echo "# Converted from $INPUT_FILE"
    echo "# Generated by ini2yaml.sh on $(date)"
    echo ""

    while IFS= read -r line || [[ -n "$line" ]]; do
        # Trim trailing whitespace but preserve leading
        line="${line%"${line##*[![:space:]]}"}"

        # Empty line
        if [[ -z "$line" ]]; then
            if $in_section; then
                flush_comments "  "
            else
                flush_comments ""
            fi
            echo ""
            continue
        fi

        # Comment line (starts with # after optional whitespace)
        if [[ "$line" =~ ^[[:space:]]*# ]]; then
            # Store comment for later output with proper indentation
            pending_comments+=("$line")
            continue
        fi

        # Section header [section_name]
        if [[ "$line" =~ ^\[([^\]]+)\]$ ]]; then
            # Flush any pending comments at the current level
            if $in_section; then
                flush_comments "  "
            else
                flush_comments ""
            fi

            current_section="${BASH_REMATCH[1]}"
            in_section=true
            echo "${current_section}:"
            continue
        fi

        # Key=value pair
        if [[ "$line" =~ ^([^=]+)=(.*)$ ]]; then
            flush_comments "  "
            key="${BASH_REMATCH[1]}"
            value="${BASH_REMATCH[2]}"
            # Trim whitespace from key
            key="$(echo "$key" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
            formatted_value=$(format_value "$value")
            echo "  ${key}: ${formatted_value}"
            continue
        fi

        # Standalone value (like port names in [server] section)
        if $in_section; then
            flush_comments "  "
            # Trim whitespace
            value="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
            if [[ -n "$value" ]]; then
                # If the value is a JSON object, wrap it in single quotes
                if [[ "$value" =~ ^\{.*\}$ ]]; then
                    echo "  - '${value}'"
                else
                    echo "  - ${value}"
                fi
            fi
        fi

    done < "$INPUT_FILE"

    # Flush any remaining comments
    if $in_section; then
        flush_comments "  "
    else
        flush_comments ""
    fi

} > "$OUTPUT_FILE"

if [[ "$OUTPUT_FILE" != "/dev/stdout" ]]; then
    echo "Converted '$INPUT_FILE' to '$OUTPUT_FILE'"
fi
