name: Extract version
description: "Extract version from BuildInfo.cpp"

outputs:
  version:
    description: "The version extracted from BuildInfo.cpp."
    value: ${{ steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Extract version
      id: version
      shell: bash
      run: |
        VERSION="$(cat src/libxrpl/protocol/BuildInfo.cpp | grep "versionString =" | awk -F '"' '{print $2}')"
        if [[ -z "${VERSION}" ]]; then
          echo 'Unable to extract version from BuildInfo.cpp.'
          exit 1
        fi
        echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"
