
#ifndef BEAST_BEASTCONFIG_HEADER
#define BEAST_BEASTCONFIG_HEADER

// beast_core flags:

#ifndef    BEAST_FORCE_DEBUG
 //#define BEAST_FORCE_DEBUG
#endif

#ifndef    BEAST_LOG_ASSERTIONS
 //#define BEAST_LOG_ASSERTIONS 1
#endif

#ifndef    BEAST_CHECK_MEMORY_LEAKS
 //#define BEAST_CHECK_MEMORY_LEAKS
#endif

#ifndef    BEAST_DONT_AUTOLINK_TO_WIN32_LIBRARIES
 //#define BEAST_DONT_AUTOLINK_TO_WIN32_LIBRARIES
#endif

#define RIPPLE_USE_NAMESPACE 0

#endif
