// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: org/xrpl/rpc/v1/xrp_ledger.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	XRPLedgerAPIService_GetLedger_FullMethodName      = "/org.xrpl.rpc.v1.XRPLedgerAPIService/GetLedger"
	XRPLedgerAPIService_GetLedgerEntry_FullMethodName = "/org.xrpl.rpc.v1.XRPLedgerAPIService/GetLedgerEntry"
	XRPLedgerAPIService_GetLedgerData_FullMethodName  = "/org.xrpl.rpc.v1.XRPLedgerAPIService/GetLedgerData"
	XRPLedgerAPIService_GetLedgerDiff_FullMethodName  = "/org.xrpl.rpc.v1.XRPLedgerAPIService/GetLedgerDiff"
)

// XRPLedgerAPIServiceClient is the client API for XRPLedgerAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// These methods are binary only methods for retrieving arbitrary ledger state
// via gRPC. These methods are used by clio, but can also be
// used by any client that wants to extract ledger state in an efficient manner.
// They do not directly mimic the JSON equivalent methods.
type XRPLedgerAPIServiceClient interface {
	// Get a specific ledger, optionally including transactions and any modified,
	// added or deleted ledger objects
	GetLedger(ctx context.Context, in *GetLedgerRequest, opts ...grpc.CallOption) (*GetLedgerResponse, error)
	// Get a specific ledger object from a specific ledger
	GetLedgerEntry(ctx context.Context, in *GetLedgerEntryRequest, opts ...grpc.CallOption) (*GetLedgerEntryResponse, error)
	// Iterate through all ledger objects in a specific ledger
	GetLedgerData(ctx context.Context, in *GetLedgerDataRequest, opts ...grpc.CallOption) (*GetLedgerDataResponse, error)
	// Get all ledger objects that are different between the two specified
	// ledgers. Note, this method has no JSON equivalent.
	GetLedgerDiff(ctx context.Context, in *GetLedgerDiffRequest, opts ...grpc.CallOption) (*GetLedgerDiffResponse, error)
}

type xRPLedgerAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewXRPLedgerAPIServiceClient(cc grpc.ClientConnInterface) XRPLedgerAPIServiceClient {
	return &xRPLedgerAPIServiceClient{cc}
}

func (c *xRPLedgerAPIServiceClient) GetLedger(ctx context.Context, in *GetLedgerRequest, opts ...grpc.CallOption) (*GetLedgerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLedgerResponse)
	err := c.cc.Invoke(ctx, XRPLedgerAPIService_GetLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xRPLedgerAPIServiceClient) GetLedgerEntry(ctx context.Context, in *GetLedgerEntryRequest, opts ...grpc.CallOption) (*GetLedgerEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLedgerEntryResponse)
	err := c.cc.Invoke(ctx, XRPLedgerAPIService_GetLedgerEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xRPLedgerAPIServiceClient) GetLedgerData(ctx context.Context, in *GetLedgerDataRequest, opts ...grpc.CallOption) (*GetLedgerDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLedgerDataResponse)
	err := c.cc.Invoke(ctx, XRPLedgerAPIService_GetLedgerData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *xRPLedgerAPIServiceClient) GetLedgerDiff(ctx context.Context, in *GetLedgerDiffRequest, opts ...grpc.CallOption) (*GetLedgerDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLedgerDiffResponse)
	err := c.cc.Invoke(ctx, XRPLedgerAPIService_GetLedgerDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XRPLedgerAPIServiceServer is the server API for XRPLedgerAPIService service.
// All implementations must embed UnimplementedXRPLedgerAPIServiceServer
// for forward compatibility.
//
// These methods are binary only methods for retrieving arbitrary ledger state
// via gRPC. These methods are used by clio, but can also be
// used by any client that wants to extract ledger state in an efficient manner.
// They do not directly mimic the JSON equivalent methods.
type XRPLedgerAPIServiceServer interface {
	// Get a specific ledger, optionally including transactions and any modified,
	// added or deleted ledger objects
	GetLedger(context.Context, *GetLedgerRequest) (*GetLedgerResponse, error)
	// Get a specific ledger object from a specific ledger
	GetLedgerEntry(context.Context, *GetLedgerEntryRequest) (*GetLedgerEntryResponse, error)
	// Iterate through all ledger objects in a specific ledger
	GetLedgerData(context.Context, *GetLedgerDataRequest) (*GetLedgerDataResponse, error)
	// Get all ledger objects that are different between the two specified
	// ledgers. Note, this method has no JSON equivalent.
	GetLedgerDiff(context.Context, *GetLedgerDiffRequest) (*GetLedgerDiffResponse, error)
	mustEmbedUnimplementedXRPLedgerAPIServiceServer()
}

// UnimplementedXRPLedgerAPIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXRPLedgerAPIServiceServer struct{}

func (UnimplementedXRPLedgerAPIServiceServer) GetLedger(context.Context, *GetLedgerRequest) (*GetLedgerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedger not implemented")
}
func (UnimplementedXRPLedgerAPIServiceServer) GetLedgerEntry(context.Context, *GetLedgerEntryRequest) (*GetLedgerEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedgerEntry not implemented")
}
func (UnimplementedXRPLedgerAPIServiceServer) GetLedgerData(context.Context, *GetLedgerDataRequest) (*GetLedgerDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedgerData not implemented")
}
func (UnimplementedXRPLedgerAPIServiceServer) GetLedgerDiff(context.Context, *GetLedgerDiffRequest) (*GetLedgerDiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLedgerDiff not implemented")
}
func (UnimplementedXRPLedgerAPIServiceServer) mustEmbedUnimplementedXRPLedgerAPIServiceServer() {}
func (UnimplementedXRPLedgerAPIServiceServer) testEmbeddedByValue()                             {}

// UnsafeXRPLedgerAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XRPLedgerAPIServiceServer will
// result in compilation errors.
type UnsafeXRPLedgerAPIServiceServer interface {
	mustEmbedUnimplementedXRPLedgerAPIServiceServer()
}

func RegisterXRPLedgerAPIServiceServer(s grpc.ServiceRegistrar, srv XRPLedgerAPIServiceServer) {
	// If the following call panics, it indicates UnimplementedXRPLedgerAPIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&XRPLedgerAPIService_ServiceDesc, srv)
}

func _XRPLedgerAPIService_GetLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XRPLedgerAPIServiceServer).GetLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XRPLedgerAPIService_GetLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XRPLedgerAPIServiceServer).GetLedger(ctx, req.(*GetLedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XRPLedgerAPIService_GetLedgerEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgerEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XRPLedgerAPIServiceServer).GetLedgerEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XRPLedgerAPIService_GetLedgerEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XRPLedgerAPIServiceServer).GetLedgerEntry(ctx, req.(*GetLedgerEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XRPLedgerAPIService_GetLedgerData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgerDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XRPLedgerAPIServiceServer).GetLedgerData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XRPLedgerAPIService_GetLedgerData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XRPLedgerAPIServiceServer).GetLedgerData(ctx, req.(*GetLedgerDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _XRPLedgerAPIService_GetLedgerDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLedgerDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XRPLedgerAPIServiceServer).GetLedgerDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: XRPLedgerAPIService_GetLedgerDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XRPLedgerAPIServiceServer).GetLedgerDiff(ctx, req.(*GetLedgerDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// XRPLedgerAPIService_ServiceDesc is the grpc.ServiceDesc for XRPLedgerAPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var XRPLedgerAPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.xrpl.rpc.v1.XRPLedgerAPIService",
	HandlerType: (*XRPLedgerAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLedger",
			Handler:    _XRPLedgerAPIService_GetLedger_Handler,
		},
		{
			MethodName: "GetLedgerEntry",
			Handler:    _XRPLedgerAPIService_GetLedgerEntry_Handler,
		},
		{
			MethodName: "GetLedgerData",
			Handler:    _XRPLedgerAPIService_GetLedgerData_Handler,
		},
		{
			MethodName: "GetLedgerDiff",
			Handler:    _XRPLedgerAPIService_GetLedgerDiff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "org/xrpl/rpc/v1/xrp_ledger.proto",
}
