// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: org/xrpl/rpc/v1/xrp_ledger.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_org_xrpl_rpc_v1_xrp_ledger_proto protoreflect.FileDescriptor

const file_org_xrpl_rpc_v1_xrp_ledger_proto_rawDesc = "" +
	"\n" +
	" org/xrpl/rpc/v1/xrp_ledger.proto\x12\x0forg.xrpl.rpc.v1\x1a org/xrpl/rpc/v1/get_ledger.proto\x1a&org/xrpl/rpc/v1/get_ledger_entry.proto\x1a%org/xrpl/rpc/v1/get_ledger_data.proto\x1a%org/xrpl/rpc/v1/get_ledger_diff.proto2\x8c\x03\n" +
	"\x13XRPLedgerAPIService\x12R\n" +
	"\tGetLedger\x12!.org.xrpl.rpc.v1.GetLedgerRequest\x1a\".org.xrpl.rpc.v1.GetLedgerResponse\x12a\n" +
	"\x0eGetLedgerEntry\x12&.org.xrpl.rpc.v1.GetLedgerEntryRequest\x1a'.org.xrpl.rpc.v1.GetLedgerEntryResponse\x12^\n" +
	"\rGetLedgerData\x12%.org.xrpl.rpc.v1.GetLedgerDataRequest\x1a&.org.xrpl.rpc.v1.GetLedgerDataResponse\x12^\n" +
	"\rGetLedgerDiff\x12%.org.xrpl.rpc.v1.GetLedgerDiffRequest\x1a&.org.xrpl.rpc.v1.GetLedgerDiffResponseBC\n" +
	"\x0forg.xrpl.rpc.v1P\x01Z.github.com/XRPLF/rippled/proto/org/xrpl/rpc/v1b\x06proto3"

var file_org_xrpl_rpc_v1_xrp_ledger_proto_goTypes = []any{
	(*GetLedgerRequest)(nil),       // 0: org.xrpl.rpc.v1.GetLedgerRequest
	(*GetLedgerEntryRequest)(nil),  // 1: org.xrpl.rpc.v1.GetLedgerEntryRequest
	(*GetLedgerDataRequest)(nil),   // 2: org.xrpl.rpc.v1.GetLedgerDataRequest
	(*GetLedgerDiffRequest)(nil),   // 3: org.xrpl.rpc.v1.GetLedgerDiffRequest
	(*GetLedgerResponse)(nil),      // 4: org.xrpl.rpc.v1.GetLedgerResponse
	(*GetLedgerEntryResponse)(nil), // 5: org.xrpl.rpc.v1.GetLedgerEntryResponse
	(*GetLedgerDataResponse)(nil),  // 6: org.xrpl.rpc.v1.GetLedgerDataResponse
	(*GetLedgerDiffResponse)(nil),  // 7: org.xrpl.rpc.v1.GetLedgerDiffResponse
}
var file_org_xrpl_rpc_v1_xrp_ledger_proto_depIdxs = []int32{
	0, // 0: org.xrpl.rpc.v1.XRPLedgerAPIService.GetLedger:input_type -> org.xrpl.rpc.v1.GetLedgerRequest
	1, // 1: org.xrpl.rpc.v1.XRPLedgerAPIService.GetLedgerEntry:input_type -> org.xrpl.rpc.v1.GetLedgerEntryRequest
	2, // 2: org.xrpl.rpc.v1.XRPLedgerAPIService.GetLedgerData:input_type -> org.xrpl.rpc.v1.GetLedgerDataRequest
	3, // 3: org.xrpl.rpc.v1.XRPLedgerAPIService.GetLedgerDiff:input_type -> org.xrpl.rpc.v1.GetLedgerDiffRequest
	4, // 4: org.xrpl.rpc.v1.XRPLedgerAPIService.GetLedger:output_type -> org.xrpl.rpc.v1.GetLedgerResponse
	5, // 5: org.xrpl.rpc.v1.XRPLedgerAPIService.GetLedgerEntry:output_type -> org.xrpl.rpc.v1.GetLedgerEntryResponse
	6, // 6: org.xrpl.rpc.v1.XRPLedgerAPIService.GetLedgerData:output_type -> org.xrpl.rpc.v1.GetLedgerDataResponse
	7, // 7: org.xrpl.rpc.v1.XRPLedgerAPIService.GetLedgerDiff:output_type -> org.xrpl.rpc.v1.GetLedgerDiffResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_org_xrpl_rpc_v1_xrp_ledger_proto_init() }
func file_org_xrpl_rpc_v1_xrp_ledger_proto_init() {
	if File_org_xrpl_rpc_v1_xrp_ledger_proto != nil {
		return
	}
	file_org_xrpl_rpc_v1_get_ledger_proto_init()
	file_org_xrpl_rpc_v1_get_ledger_entry_proto_init()
	file_org_xrpl_rpc_v1_get_ledger_data_proto_init()
	file_org_xrpl_rpc_v1_get_ledger_diff_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_org_xrpl_rpc_v1_xrp_ledger_proto_rawDesc), len(file_org_xrpl_rpc_v1_xrp_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_xrpl_rpc_v1_xrp_ledger_proto_goTypes,
		DependencyIndexes: file_org_xrpl_rpc_v1_xrp_ledger_proto_depIdxs,
	}.Build()
	File_org_xrpl_rpc_v1_xrp_ledger_proto = out.File
	file_org_xrpl_rpc_v1_xrp_ledger_proto_goTypes = nil
	file_org_xrpl_rpc_v1_xrp_ledger_proto_depIdxs = nil
}
