name: conan-configure

inputs:
  conan_global_conf:
    description: 'The contents of the global Conan configuration file.'
    required: true
    type: string

# Install the Conan profiles and log into the specified remote. We first remove
# the remote if it already exists, which can occur on self-hosted runners where
# the workspace is not cleaned up between runs.
runs:
  using: composite
  steps:
    - name: Check configuration
      shell: bash
      run: |
        echo "Checking Conan version."
        conan --version
    - name: Install Conan profile
      shell: bash
      run: |
        echo "${{ inputs.conan_global_conf }}" >> $(conan config home)/global.conf
        conan config install conan/profiles/default -tf $(conan config home)/profiles/
        echo "Installed Conan profile:"
        conan profile show
    - name: Add Conan remote
      shell: bash
      run: |
        if conan remote list | grep -q '${{ vars.CONAN_REMOTE_NAME }}'; then
            conan remote remove ${{ vars.CONAN_REMOTE_NAME }}
            echo "Removed Conan remote '${{ vars.CONAN_REMOTE_NAME }}'."
        fi
        conan remote add --index 0 ${{ vars.CONAN_REMOTE_NAME }} ${{ vars.CONAN_REMOTE_URL }}
        echo "Added new conan remote '${{ vars.CONAN_REMOTE_NAME }}' at ${{ vars.CONAN_REMOTE_URL }}."
    - name: Log into Conan remote
      shell: bash
      run: |
        conan remote login ${{ vars.CONAN_REMOTE_NAME }} ${{ vars.CONAN_USERNAME }} --password "${{ secrets.CONAN_PASSWORD }}"
        conan remote list-users
