# The following variable is specific to this backend and its correct
# values might depend on your environment - feel free to set it accordingly.

BOOSTINCLUDEDIR =
SQLITE3INCLUDEDIR = 
SQLITE3LIBDIR = -L/usr/lib
SQLITE3LIBS = -lsqlite3

# The rest of the Makefile is independent of the target environment.

COMPILER = g++
CXXFLAGS = -Wall -pedantic -Wno-long-long
INCLUDEDIRS = -I.. -I../../../core -I../../../core/test ${SQLITE3INCLUDEDIR} ${BOOSTINCLUDEDIR}
LIBDIRS = -L.. -L../../../core ${SQLITE3LIBDIR}
LIBS = -lsoci_core -lsoci_sqlite3 -ldl ${SQLITE3LIBS}


test-sqlite3 : test-sqlite3.cpp
	${COMPILER} -o $@ $? ${CXXFLAGS} ${INCLUDEDIRS} ${LIBDIRS} ${LIBS}


clean :
	rm -f test-sqlite3
