sudo: false
language: cpp

env:
  global:
    # Maintenance note: to move to a new version
    # of boost, update both BOOST_ROOT and BOOST_URL.
    # Note that for simplicity, BOOST_ROOT's final
    # namepart must match the folder name internal
    # to boost's .tar.gz.
    - BOOST_ROOT=$HOME/boost_1_60_0
    - BOOST_URL='http://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fboost%2Ffiles%2Fboost%2F1.60.0%2Fboost_1_60_0.tar.gz&ts=1460417589&use_mirror=netix'
packages: &gcc5_pkgs
  - gcc-5
  - g++-5
  - python-software-properties
  - protobuf-compiler
  - libstdc++6
  - binutils-gold
  # Provides a backtrace if the unittests crash
  - gdb

packages: &clang36_pkgs
  - clang-3.6
  - g++-5
  - python-software-properties
  - libssl-dev
  - libstdc++6
  - binutils-gold
  # Provides a backtrace if the unittests crash
  - gdb

matrix:
  include:
    - compiler: gcc
      env: GCC_VER=5 VARIANT=debug
      addons: &ao_gcc5
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: *gcc5_pkgs

    - compiler: gcc
      env: GCC_VER=5 VARIANT=release
      addons: *ao_gcc5

    - compiler: clang
      env: GCC_VER=5 VARIANT=debug CLANG_VER=3.6
      addons: &ao_clang36
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
          packages: *clang36_pkgs

    - compiler: clang
      env: GCC_VER=5 VARIANT=release CLANG_VER=3.6
      addons: *ao_clang36

cache:
  directories:
  - $BOOST_ROOT

before_install:
  - scripts/install-dependencies.sh

script:
  - scripts/build-and-test.sh

notifications:
  email:
    false
