#pragma once

#include <xrpld/rpc/handlers/ledger/Ledger.h>

namespace xrpl {

json::Value
doAccountCurrencies(RPC::JsonContext&);
json::Value
doAccountInfo(RPC::JsonContext&);
json::Value
doAccountLines(RPC::JsonContext&);
json::Value
doAccountChannels(RPC::JsonContext&);
json::Value
doAccountNFTs(RPC::JsonContext&);
json::Value
doAccountObjects(RPC::JsonContext&);
json::Value
doAccountOffers(RPC::JsonContext&);
json::Value
doAccountTx(RPC::JsonContext&);
json::Value
doAMMInfo(RPC::JsonContext&);
json::Value
doBookOffers(RPC::JsonContext&);
json::Value
doBookChanges(RPC::JsonContext&);
json::Value
doBlackList(RPC::JsonContext&);
json::Value
doCanDelete(RPC::JsonContext&);
json::Value
doChannelAuthorize(RPC::JsonContext&);
json::Value
doChannelVerify(RPC::JsonContext&);
json::Value
doConnect(RPC::JsonContext&);
json::Value
doConsensusInfo(RPC::JsonContext&);
json::Value
doDepositAuthorized(RPC::JsonContext&);
json::Value
doFeature(RPC::JsonContext&);
json::Value
doFee(RPC::JsonContext&);
json::Value
doFetchInfo(RPC::JsonContext&);
json::Value
doGatewayBalances(RPC::JsonContext&);
json::Value
doGetCounts(RPC::JsonContext&);
json::Value
doGetAggregatePrice(RPC::JsonContext&);
json::Value
doLedgerAccept(RPC::JsonContext&);
json::Value
doLedgerCleaner(RPC::JsonContext&);
json::Value
doLedgerClosed(RPC::JsonContext&);
json::Value
doLedgerCurrent(RPC::JsonContext&);
json::Value
doLedgerData(RPC::JsonContext&);
json::Value
doLedgerEntry(RPC::JsonContext&);
json::Value
doLedgerHeader(RPC::JsonContext&);
json::Value
doLedgerRequest(RPC::JsonContext&);
json::Value
doLogLevel(RPC::JsonContext&);
json::Value
doLogRotate(RPC::JsonContext&);
json::Value
doManifest(RPC::JsonContext&);
json::Value
doNFTBuyOffers(RPC::JsonContext&);
json::Value
doNFTSellOffers(RPC::JsonContext&);
json::Value
doNoRippleCheck(RPC::JsonContext&);
json::Value
doOwnerInfo(RPC::JsonContext&);
json::Value
doPathFind(RPC::JsonContext&);
json::Value
doPause(RPC::JsonContext&);
json::Value
doPeers(RPC::JsonContext&);
json::Value
doPing(RPC::JsonContext&);
json::Value
doPrint(RPC::JsonContext&);
json::Value
doRandom(RPC::JsonContext&);
json::Value
doResume(RPC::JsonContext&);
json::Value
doPeerReservationsAdd(RPC::JsonContext&);
json::Value
doPeerReservationsDel(RPC::JsonContext&);
json::Value
doPeerReservationsList(RPC::JsonContext&);
json::Value
doRipplePathFind(RPC::JsonContext&);
json::Value
doServerDefinitions(RPC::JsonContext&);
json::Value
doServerInfo(RPC::JsonContext&);  // for humans
json::Value
doServerState(RPC::JsonContext&);  // for machines
json::Value
doSign(RPC::JsonContext&);
json::Value
doSignFor(RPC::JsonContext&);
json::Value
doSimulate(RPC::JsonContext&);
json::Value
doStop(RPC::JsonContext&);
json::Value
doSubmit(RPC::JsonContext&);
json::Value
doSubmitMultiSigned(RPC::JsonContext&);
json::Value
doSubscribe(RPC::JsonContext&);
json::Value
doTransactionEntry(RPC::JsonContext&);
json::Value
doTxJson(RPC::JsonContext&);
json::Value
doTxHistory(RPC::JsonContext&);
json::Value
doTxReduceRelay(RPC::JsonContext&);
json::Value
doUnlList(RPC::JsonContext&);
json::Value
doUnsubscribe(RPC::JsonContext&);
json::Value
doValidationCreate(RPC::JsonContext&);
json::Value
doWalletPropose(RPC::JsonContext&);
json::Value
doValidators(RPC::JsonContext&);
json::Value
doValidatorListSites(RPC::JsonContext&);
json::Value
doValidatorInfo(RPC::JsonContext&);
json::Value
doVaultInfo(RPC::JsonContext&);
}  // namespace xrpl
