// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: org/xrpl/rpc/v1/ledger.proto
// Protobuf C++ Version: 6.33.5

#ifndef org_2fxrpl_2frpc_2fv1_2fledger_2eproto_2epb_2eh
#define org_2fxrpl_2frpc_2fv1_2fledger_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_org_2fxrpl_2frpc_2fv1_2fledger_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_org_2fxrpl_2frpc_2fv1_2fledger_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_org_2fxrpl_2frpc_2fv1_2fledger_2eproto;
}  // extern "C"
namespace org {
namespace xrpl {
namespace rpc {
namespace v1 {
enum LedgerSpecifier_Shortcut : int;
extern const uint32_t LedgerSpecifier_Shortcut_internal_data_[];
enum RawLedgerObject_ModificationType : int;
extern const uint32_t RawLedgerObject_ModificationType_internal_data_[];
class BookSuccessor;
struct BookSuccessorDefaultTypeInternal;
extern BookSuccessorDefaultTypeInternal _BookSuccessor_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BookSuccessor_class_data_;
class LedgerSpecifier;
struct LedgerSpecifierDefaultTypeInternal;
extern LedgerSpecifierDefaultTypeInternal _LedgerSpecifier_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull LedgerSpecifier_class_data_;
class RawLedgerObject;
struct RawLedgerObjectDefaultTypeInternal;
extern RawLedgerObjectDefaultTypeInternal _RawLedgerObject_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RawLedgerObject_class_data_;
class RawLedgerObjects;
struct RawLedgerObjectsDefaultTypeInternal;
extern RawLedgerObjectsDefaultTypeInternal _RawLedgerObjects_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull RawLedgerObjects_class_data_;
}  // namespace v1
}  // namespace rpc
}  // namespace xrpl
}  // namespace org
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut_internal_data_>
    internal::EnumTraitsImpl::value<::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut>;
template <>
internal::EnumTraitsT<::org::xrpl::rpc::v1::RawLedgerObject_ModificationType_internal_data_>
    internal::EnumTraitsImpl::value<::org::xrpl::rpc::v1::RawLedgerObject_ModificationType>;
}  // namespace protobuf
}  // namespace google

namespace org {
namespace xrpl {
namespace rpc {
namespace v1 {
enum LedgerSpecifier_Shortcut : int {
  LedgerSpecifier_Shortcut_SHORTCUT_UNSPECIFIED = 0,
  LedgerSpecifier_Shortcut_SHORTCUT_VALIDATED = 1,
  LedgerSpecifier_Shortcut_SHORTCUT_CLOSED = 2,
  LedgerSpecifier_Shortcut_SHORTCUT_CURRENT = 3,
  LedgerSpecifier_Shortcut_LedgerSpecifier_Shortcut_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  LedgerSpecifier_Shortcut_LedgerSpecifier_Shortcut_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t LedgerSpecifier_Shortcut_internal_data_[];
inline constexpr LedgerSpecifier_Shortcut LedgerSpecifier_Shortcut_Shortcut_MIN =
    static_cast<LedgerSpecifier_Shortcut>(0);
inline constexpr LedgerSpecifier_Shortcut LedgerSpecifier_Shortcut_Shortcut_MAX =
    static_cast<LedgerSpecifier_Shortcut>(3);
inline bool LedgerSpecifier_Shortcut_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int LedgerSpecifier_Shortcut_Shortcut_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL LedgerSpecifier_Shortcut_descriptor();
template <typename T>
const ::std::string& LedgerSpecifier_Shortcut_Name(T value) {
  static_assert(::std::is_same<T, LedgerSpecifier_Shortcut>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Shortcut_Name().");
  return LedgerSpecifier_Shortcut_Name(static_cast<LedgerSpecifier_Shortcut>(value));
}
template <>
inline const ::std::string& LedgerSpecifier_Shortcut_Name(LedgerSpecifier_Shortcut value) {
  return ::google::protobuf::internal::NameOfDenseEnum<LedgerSpecifier_Shortcut_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool LedgerSpecifier_Shortcut_Parse(
    ::absl::string_view name, LedgerSpecifier_Shortcut* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<LedgerSpecifier_Shortcut>(LedgerSpecifier_Shortcut_descriptor(), name,
                                           value);
}
enum RawLedgerObject_ModificationType : int {
  RawLedgerObject_ModificationType_UNSPECIFIED = 0,
  RawLedgerObject_ModificationType_CREATED = 1,
  RawLedgerObject_ModificationType_MODIFIED = 2,
  RawLedgerObject_ModificationType_DELETED = 3,
  RawLedgerObject_ModificationType_RawLedgerObject_ModificationType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  RawLedgerObject_ModificationType_RawLedgerObject_ModificationType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t RawLedgerObject_ModificationType_internal_data_[];
inline constexpr RawLedgerObject_ModificationType RawLedgerObject_ModificationType_ModificationType_MIN =
    static_cast<RawLedgerObject_ModificationType>(0);
inline constexpr RawLedgerObject_ModificationType RawLedgerObject_ModificationType_ModificationType_MAX =
    static_cast<RawLedgerObject_ModificationType>(3);
inline bool RawLedgerObject_ModificationType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int RawLedgerObject_ModificationType_ModificationType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL RawLedgerObject_ModificationType_descriptor();
template <typename T>
const ::std::string& RawLedgerObject_ModificationType_Name(T value) {
  static_assert(::std::is_same<T, RawLedgerObject_ModificationType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ModificationType_Name().");
  return RawLedgerObject_ModificationType_Name(static_cast<RawLedgerObject_ModificationType>(value));
}
template <>
inline const ::std::string& RawLedgerObject_ModificationType_Name(RawLedgerObject_ModificationType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<RawLedgerObject_ModificationType_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool RawLedgerObject_ModificationType_Parse(
    ::absl::string_view name, RawLedgerObject_ModificationType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<RawLedgerObject_ModificationType>(RawLedgerObject_ModificationType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class RawLedgerObject final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:org.xrpl.rpc.v1.RawLedgerObject) */ {
 public:
  inline RawLedgerObject() : RawLedgerObject(nullptr) {}
  ~RawLedgerObject() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RawLedgerObject* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RawLedgerObject));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RawLedgerObject(::google::protobuf::internal::ConstantInitialized);

  inline RawLedgerObject(const RawLedgerObject& from) : RawLedgerObject(nullptr, from) {}
  inline RawLedgerObject(RawLedgerObject&& from) noexcept
      : RawLedgerObject(nullptr, ::std::move(from)) {}
  inline RawLedgerObject& operator=(const RawLedgerObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline RawLedgerObject& operator=(RawLedgerObject&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RawLedgerObject& default_instance() {
    return *reinterpret_cast<const RawLedgerObject*>(
        &_RawLedgerObject_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(RawLedgerObject& a, RawLedgerObject& b) { a.Swap(&b); }
  inline void Swap(RawLedgerObject* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RawLedgerObject* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RawLedgerObject* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RawLedgerObject>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RawLedgerObject& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RawLedgerObject& from) { RawLedgerObject::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RawLedgerObject* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "org.xrpl.rpc.v1.RawLedgerObject"; }

  explicit RawLedgerObject(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RawLedgerObject(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RawLedgerObject& from);
  RawLedgerObject(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RawLedgerObject&& from) noexcept
      : RawLedgerObject(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using ModificationType = RawLedgerObject_ModificationType;
  static constexpr ModificationType UNSPECIFIED = RawLedgerObject_ModificationType_UNSPECIFIED;
  static constexpr ModificationType CREATED = RawLedgerObject_ModificationType_CREATED;
  static constexpr ModificationType MODIFIED = RawLedgerObject_ModificationType_MODIFIED;
  static constexpr ModificationType DELETED = RawLedgerObject_ModificationType_DELETED;
  static inline bool ModificationType_IsValid(int value) {
    return RawLedgerObject_ModificationType_IsValid(value);
  }
  static constexpr ModificationType ModificationType_MIN = RawLedgerObject_ModificationType_ModificationType_MIN;
  static constexpr ModificationType ModificationType_MAX = RawLedgerObject_ModificationType_ModificationType_MAX;
  static constexpr int ModificationType_ARRAYSIZE = RawLedgerObject_ModificationType_ModificationType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ModificationType_descriptor() {
    return RawLedgerObject_ModificationType_descriptor();
  }
  template <typename T>
  static inline const ::std::string& ModificationType_Name(T value) {
    return RawLedgerObject_ModificationType_Name(value);
  }
  static inline bool ModificationType_Parse(
      ::absl::string_view name, ModificationType* PROTOBUF_NONNULL value) {
    return RawLedgerObject_ModificationType_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kDataFieldNumber = 1,
    kKeyFieldNumber = 2,
    kPredecessorFieldNumber = 4,
    kSuccessorFieldNumber = 5,
    kModTypeFieldNumber = 3,
  };
  // bytes data = 1;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // bytes key = 2;
  void clear_key() ;
  const ::std::string& key() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_key(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_key();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_key();
  void set_allocated_key(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_key() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_key(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_key();

  public:
  // bytes predecessor = 4;
  void clear_predecessor() ;
  const ::std::string& predecessor() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_predecessor(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_predecessor();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_predecessor();
  void set_allocated_predecessor(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_predecessor() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_predecessor(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_predecessor();

  public:
  // bytes successor = 5;
  void clear_successor() ;
  const ::std::string& successor() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_successor(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_successor();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_successor();
  void set_allocated_successor(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_successor() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_successor(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_successor();

  public:
  // .org.xrpl.rpc.v1.RawLedgerObject.ModificationType mod_type = 3;
  void clear_mod_type() ;
  ::org::xrpl::rpc::v1::RawLedgerObject_ModificationType mod_type() const;
  void set_mod_type(::org::xrpl::rpc::v1::RawLedgerObject_ModificationType value);

  private:
  ::org::xrpl::rpc::v1::RawLedgerObject_ModificationType _internal_mod_type() const;
  void _internal_set_mod_type(::org::xrpl::rpc::v1::RawLedgerObject_ModificationType value);

  public:
  // @@protoc_insertion_point(class_scope:org.xrpl.rpc.v1.RawLedgerObject)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RawLedgerObject& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::google::protobuf::internal::ArenaStringPtr key_;
    ::google::protobuf::internal::ArenaStringPtr predecessor_;
    ::google::protobuf::internal::ArenaStringPtr successor_;
    int mod_type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_org_2fxrpl_2frpc_2fv1_2fledger_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RawLedgerObject_class_data_;
// -------------------------------------------------------------------

class LedgerSpecifier final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:org.xrpl.rpc.v1.LedgerSpecifier) */ {
 public:
  inline LedgerSpecifier() : LedgerSpecifier(nullptr) {}
  ~LedgerSpecifier() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LedgerSpecifier* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LedgerSpecifier));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LedgerSpecifier(::google::protobuf::internal::ConstantInitialized);

  inline LedgerSpecifier(const LedgerSpecifier& from) : LedgerSpecifier(nullptr, from) {}
  inline LedgerSpecifier(LedgerSpecifier&& from) noexcept
      : LedgerSpecifier(nullptr, ::std::move(from)) {}
  inline LedgerSpecifier& operator=(const LedgerSpecifier& from) {
    CopyFrom(from);
    return *this;
  }
  inline LedgerSpecifier& operator=(LedgerSpecifier&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LedgerSpecifier& default_instance() {
    return *reinterpret_cast<const LedgerSpecifier*>(
        &_LedgerSpecifier_default_instance_);
  }
  enum LedgerCase {
    kShortcut = 1,
    kSequence = 2,
    kHash = 3,
    LEDGER_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(LedgerSpecifier& a, LedgerSpecifier& b) { a.Swap(&b); }
  inline void Swap(LedgerSpecifier* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LedgerSpecifier* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LedgerSpecifier* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LedgerSpecifier>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LedgerSpecifier& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LedgerSpecifier& from) { LedgerSpecifier::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LedgerSpecifier* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "org.xrpl.rpc.v1.LedgerSpecifier"; }

  explicit LedgerSpecifier(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  LedgerSpecifier(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LedgerSpecifier& from);
  LedgerSpecifier(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, LedgerSpecifier&& from) noexcept
      : LedgerSpecifier(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Shortcut = LedgerSpecifier_Shortcut;
  static constexpr Shortcut SHORTCUT_UNSPECIFIED = LedgerSpecifier_Shortcut_SHORTCUT_UNSPECIFIED;
  static constexpr Shortcut SHORTCUT_VALIDATED = LedgerSpecifier_Shortcut_SHORTCUT_VALIDATED;
  static constexpr Shortcut SHORTCUT_CLOSED = LedgerSpecifier_Shortcut_SHORTCUT_CLOSED;
  static constexpr Shortcut SHORTCUT_CURRENT = LedgerSpecifier_Shortcut_SHORTCUT_CURRENT;
  static inline bool Shortcut_IsValid(int value) {
    return LedgerSpecifier_Shortcut_IsValid(value);
  }
  static constexpr Shortcut Shortcut_MIN = LedgerSpecifier_Shortcut_Shortcut_MIN;
  static constexpr Shortcut Shortcut_MAX = LedgerSpecifier_Shortcut_Shortcut_MAX;
  static constexpr int Shortcut_ARRAYSIZE = LedgerSpecifier_Shortcut_Shortcut_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Shortcut_descriptor() {
    return LedgerSpecifier_Shortcut_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Shortcut_Name(T value) {
    return LedgerSpecifier_Shortcut_Name(value);
  }
  static inline bool Shortcut_Parse(
      ::absl::string_view name, Shortcut* PROTOBUF_NONNULL value) {
    return LedgerSpecifier_Shortcut_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kShortcutFieldNumber = 1,
    kSequenceFieldNumber = 2,
    kHashFieldNumber = 3,
  };
  // .org.xrpl.rpc.v1.LedgerSpecifier.Shortcut shortcut = 1;
  bool has_shortcut() const;
  void clear_shortcut() ;
  ::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut shortcut() const;
  void set_shortcut(::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut value);

  private:
  ::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut _internal_shortcut() const;
  void _internal_set_shortcut(::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut value);

  public:
  // uint32 sequence = 2;
  bool has_sequence() const;
  void clear_sequence() ;
  ::uint32_t sequence() const;
  void set_sequence(::uint32_t value);

  private:
  ::uint32_t _internal_sequence() const;
  void _internal_set_sequence(::uint32_t value);

  public:
  // bytes hash = 3;
  bool has_hash() const;
  void clear_hash() ;
  const ::std::string& hash() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_hash(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_hash();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_hash();
  void set_allocated_hash(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_hash() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_hash(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_hash();

  public:
  void clear_ledger();
  LedgerCase ledger_case() const;
  // @@protoc_insertion_point(class_scope:org.xrpl.rpc.v1.LedgerSpecifier)
 private:
  class _Internal;
  void set_has_shortcut();
  void set_has_sequence();
  void set_has_hash();
  inline bool has_ledger() const;
  inline void clear_has_ledger();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const LedgerSpecifier& from_msg);
    union LedgerUnion {
      constexpr LedgerUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      int shortcut_;
      ::uint32_t sequence_;
      ::google::protobuf::internal::ArenaStringPtr hash_;
    } ledger_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_org_2fxrpl_2frpc_2fv1_2fledger_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull LedgerSpecifier_class_data_;
// -------------------------------------------------------------------

class BookSuccessor final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:org.xrpl.rpc.v1.BookSuccessor) */ {
 public:
  inline BookSuccessor() : BookSuccessor(nullptr) {}
  ~BookSuccessor() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BookSuccessor* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BookSuccessor));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BookSuccessor(::google::protobuf::internal::ConstantInitialized);

  inline BookSuccessor(const BookSuccessor& from) : BookSuccessor(nullptr, from) {}
  inline BookSuccessor(BookSuccessor&& from) noexcept
      : BookSuccessor(nullptr, ::std::move(from)) {}
  inline BookSuccessor& operator=(const BookSuccessor& from) {
    CopyFrom(from);
    return *this;
  }
  inline BookSuccessor& operator=(BookSuccessor&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BookSuccessor& default_instance() {
    return *reinterpret_cast<const BookSuccessor*>(
        &_BookSuccessor_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(BookSuccessor& a, BookSuccessor& b) { a.Swap(&b); }
  inline void Swap(BookSuccessor* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BookSuccessor* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BookSuccessor* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BookSuccessor>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BookSuccessor& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BookSuccessor& from) { BookSuccessor::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BookSuccessor* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "org.xrpl.rpc.v1.BookSuccessor"; }

  explicit BookSuccessor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BookSuccessor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BookSuccessor& from);
  BookSuccessor(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BookSuccessor&& from) noexcept
      : BookSuccessor(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kBookBaseFieldNumber = 1,
    kFirstBookFieldNumber = 2,
  };
  // bytes book_base = 1;
  void clear_book_base() ;
  const ::std::string& book_base() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_book_base(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_book_base();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_book_base();
  void set_allocated_book_base(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_book_base() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_book_base(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_book_base();

  public:
  // bytes first_book = 2;
  void clear_first_book() ;
  const ::std::string& first_book() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_first_book(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_first_book();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_first_book();
  void set_allocated_first_book(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_first_book() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_first_book(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_first_book();

  public:
  // @@protoc_insertion_point(class_scope:org.xrpl.rpc.v1.BookSuccessor)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BookSuccessor& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr book_base_;
    ::google::protobuf::internal::ArenaStringPtr first_book_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_org_2fxrpl_2frpc_2fv1_2fledger_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BookSuccessor_class_data_;
// -------------------------------------------------------------------

class RawLedgerObjects final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:org.xrpl.rpc.v1.RawLedgerObjects) */ {
 public:
  inline RawLedgerObjects() : RawLedgerObjects(nullptr) {}
  ~RawLedgerObjects() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(RawLedgerObjects* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(RawLedgerObjects));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR RawLedgerObjects(::google::protobuf::internal::ConstantInitialized);

  inline RawLedgerObjects(const RawLedgerObjects& from) : RawLedgerObjects(nullptr, from) {}
  inline RawLedgerObjects(RawLedgerObjects&& from) noexcept
      : RawLedgerObjects(nullptr, ::std::move(from)) {}
  inline RawLedgerObjects& operator=(const RawLedgerObjects& from) {
    CopyFrom(from);
    return *this;
  }
  inline RawLedgerObjects& operator=(RawLedgerObjects&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RawLedgerObjects& default_instance() {
    return *reinterpret_cast<const RawLedgerObjects*>(
        &_RawLedgerObjects_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(RawLedgerObjects& a, RawLedgerObjects& b) { a.Swap(&b); }
  inline void Swap(RawLedgerObjects* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RawLedgerObjects* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RawLedgerObjects* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<RawLedgerObjects>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RawLedgerObjects& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const RawLedgerObjects& from) { RawLedgerObjects::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(RawLedgerObjects* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "org.xrpl.rpc.v1.RawLedgerObjects"; }

  explicit RawLedgerObjects(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  RawLedgerObjects(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const RawLedgerObjects& from);
  RawLedgerObjects(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, RawLedgerObjects&& from) noexcept
      : RawLedgerObjects(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kObjectsFieldNumber = 1,
  };
  // repeated .org.xrpl.rpc.v1.RawLedgerObject objects = 1;
  int objects_size() const;
  private:
  int _internal_objects_size() const;

  public:
  void clear_objects() ;
  ::org::xrpl::rpc::v1::RawLedgerObject* PROTOBUF_NONNULL mutable_objects(int index);
  ::google::protobuf::RepeatedPtrField<::org::xrpl::rpc::v1::RawLedgerObject>* PROTOBUF_NONNULL mutable_objects();

  private:
  const ::google::protobuf::RepeatedPtrField<::org::xrpl::rpc::v1::RawLedgerObject>& _internal_objects() const;
  ::google::protobuf::RepeatedPtrField<::org::xrpl::rpc::v1::RawLedgerObject>* PROTOBUF_NONNULL _internal_mutable_objects();
  public:
  const ::org::xrpl::rpc::v1::RawLedgerObject& objects(int index) const;
  ::org::xrpl::rpc::v1::RawLedgerObject* PROTOBUF_NONNULL add_objects();
  const ::google::protobuf::RepeatedPtrField<::org::xrpl::rpc::v1::RawLedgerObject>& objects() const;
  // @@protoc_insertion_point(class_scope:org.xrpl.rpc.v1.RawLedgerObjects)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const RawLedgerObjects& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::org::xrpl::rpc::v1::RawLedgerObject > objects_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_org_2fxrpl_2frpc_2fv1_2fledger_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull RawLedgerObjects_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// LedgerSpecifier

// .org.xrpl.rpc.v1.LedgerSpecifier.Shortcut shortcut = 1;
inline bool LedgerSpecifier::has_shortcut() const {
  return ledger_case() == kShortcut;
}
inline void LedgerSpecifier::set_has_shortcut() {
  _impl_._oneof_case_[0] = kShortcut;
}
inline void LedgerSpecifier::clear_shortcut() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (ledger_case() == kShortcut) {
    _impl_.ledger_.shortcut_ = 0;
    clear_has_ledger();
  }
}
inline ::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut LedgerSpecifier::shortcut() const {
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.LedgerSpecifier.shortcut)
  return _internal_shortcut();
}
inline void LedgerSpecifier::set_shortcut(::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut value) {
  if (ledger_case() != kShortcut) {
    clear_ledger();
    set_has_shortcut();
  }
  _impl_.ledger_.shortcut_ = value;
  // @@protoc_insertion_point(field_set:org.xrpl.rpc.v1.LedgerSpecifier.shortcut)
}
inline ::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut LedgerSpecifier::_internal_shortcut() const {
  if (ledger_case() == kShortcut) {
    return static_cast<::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut>(_impl_.ledger_.shortcut_);
  }
  return static_cast<::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut>(0);
}

// uint32 sequence = 2;
inline bool LedgerSpecifier::has_sequence() const {
  return ledger_case() == kSequence;
}
inline void LedgerSpecifier::set_has_sequence() {
  _impl_._oneof_case_[0] = kSequence;
}
inline void LedgerSpecifier::clear_sequence() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (ledger_case() == kSequence) {
    _impl_.ledger_.sequence_ = 0u;
    clear_has_ledger();
  }
}
inline ::uint32_t LedgerSpecifier::sequence() const {
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.LedgerSpecifier.sequence)
  return _internal_sequence();
}
inline void LedgerSpecifier::set_sequence(::uint32_t value) {
  if (ledger_case() != kSequence) {
    clear_ledger();
    set_has_sequence();
  }
  _impl_.ledger_.sequence_ = value;
  // @@protoc_insertion_point(field_set:org.xrpl.rpc.v1.LedgerSpecifier.sequence)
}
inline ::uint32_t LedgerSpecifier::_internal_sequence() const {
  if (ledger_case() == kSequence) {
    return _impl_.ledger_.sequence_;
  }
  return 0u;
}

// bytes hash = 3;
inline bool LedgerSpecifier::has_hash() const {
  return ledger_case() == kHash;
}
inline void LedgerSpecifier::set_has_hash() {
  _impl_._oneof_case_[0] = kHash;
}
inline void LedgerSpecifier::clear_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (ledger_case() == kHash) {
    _impl_.ledger_.hash_.Destroy();
    clear_has_ledger();
  }
}
inline const ::std::string& LedgerSpecifier::hash() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.LedgerSpecifier.hash)
  return _internal_hash();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void LedgerSpecifier::set_hash(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (ledger_case() != kHash) {
    clear_ledger();

    set_has_hash();
    _impl_.ledger_.hash_.InitDefault();
  }
  _impl_.ledger_.hash_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:org.xrpl.rpc.v1.LedgerSpecifier.hash)
}
inline ::std::string* PROTOBUF_NONNULL LedgerSpecifier::mutable_hash()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  if (ledger_case() != kHash) {
    clear_ledger();

    set_has_hash();
    _impl_.ledger_.hash_.InitDefault();
  }
  ::std::string* _s = _internal_mutable_hash();
  // @@protoc_insertion_point(field_mutable:org.xrpl.rpc.v1.LedgerSpecifier.hash)
  return _s;
}
inline const ::std::string& LedgerSpecifier::_internal_hash() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  if (ledger_case() != kHash) {
    return ::google::protobuf::internal::GetEmptyStringAlreadyInited();
  }
  return _impl_.ledger_.hash_.Get();
}
inline void LedgerSpecifier::_internal_set_hash(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ledger_.hash_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL LedgerSpecifier::_internal_mutable_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ledger_.hash_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE LedgerSpecifier::release_hash() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:org.xrpl.rpc.v1.LedgerSpecifier.hash)
  if (ledger_case() != kHash) {
    return nullptr;
  }
  clear_has_ledger();
  return _impl_.ledger_.hash_.Release();
}
inline void LedgerSpecifier::set_allocated_hash(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (has_ledger()) {
    clear_ledger();
  }
  if (value != nullptr) {
    set_has_hash();
    _impl_.ledger_.hash_.InitAllocated(value, GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:org.xrpl.rpc.v1.LedgerSpecifier.hash)
}

inline bool LedgerSpecifier::has_ledger() const {
  return ledger_case() != LEDGER_NOT_SET;
}
inline void LedgerSpecifier::clear_has_ledger() {
  _impl_._oneof_case_[0] = LEDGER_NOT_SET;
}
inline LedgerSpecifier::LedgerCase LedgerSpecifier::ledger_case() const {
  return LedgerSpecifier::LedgerCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// RawLedgerObject

// bytes data = 1;
inline void RawLedgerObject::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& RawLedgerObject::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.RawLedgerObject.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RawLedgerObject::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:org.xrpl.rpc.v1.RawLedgerObject.data)
}
inline ::std::string* PROTOBUF_NONNULL RawLedgerObject::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:org.xrpl.rpc.v1.RawLedgerObject.data)
  return _s;
}
inline const ::std::string& RawLedgerObject::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void RawLedgerObject::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RawLedgerObject::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RawLedgerObject::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:org.xrpl.rpc.v1.RawLedgerObject.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void RawLedgerObject::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:org.xrpl.rpc.v1.RawLedgerObject.data)
}

// bytes key = 2;
inline void RawLedgerObject::clear_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& RawLedgerObject::key() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.RawLedgerObject.key)
  return _internal_key();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RawLedgerObject::set_key(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.key_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:org.xrpl.rpc.v1.RawLedgerObject.key)
}
inline ::std::string* PROTOBUF_NONNULL RawLedgerObject::mutable_key()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:org.xrpl.rpc.v1.RawLedgerObject.key)
  return _s;
}
inline const ::std::string& RawLedgerObject::_internal_key() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.key_.Get();
}
inline void RawLedgerObject::_internal_set_key(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.key_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RawLedgerObject::_internal_mutable_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.key_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RawLedgerObject::release_key() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:org.xrpl.rpc.v1.RawLedgerObject.key)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.key_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.key_.Set("", GetArena());
  }
  return released;
}
inline void RawLedgerObject::set_allocated_key(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.key_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:org.xrpl.rpc.v1.RawLedgerObject.key)
}

// .org.xrpl.rpc.v1.RawLedgerObject.ModificationType mod_type = 3;
inline void RawLedgerObject::clear_mod_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mod_type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::org::xrpl::rpc::v1::RawLedgerObject_ModificationType RawLedgerObject::mod_type() const {
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.RawLedgerObject.mod_type)
  return _internal_mod_type();
}
inline void RawLedgerObject::set_mod_type(::org::xrpl::rpc::v1::RawLedgerObject_ModificationType value) {
  _internal_set_mod_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:org.xrpl.rpc.v1.RawLedgerObject.mod_type)
}
inline ::org::xrpl::rpc::v1::RawLedgerObject_ModificationType RawLedgerObject::_internal_mod_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::org::xrpl::rpc::v1::RawLedgerObject_ModificationType>(_impl_.mod_type_);
}
inline void RawLedgerObject::_internal_set_mod_type(::org::xrpl::rpc::v1::RawLedgerObject_ModificationType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.mod_type_ = value;
}

// bytes predecessor = 4;
inline void RawLedgerObject::clear_predecessor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.predecessor_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& RawLedgerObject::predecessor() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.RawLedgerObject.predecessor)
  return _internal_predecessor();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RawLedgerObject::set_predecessor(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.predecessor_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:org.xrpl.rpc.v1.RawLedgerObject.predecessor)
}
inline ::std::string* PROTOBUF_NONNULL RawLedgerObject::mutable_predecessor()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_predecessor();
  // @@protoc_insertion_point(field_mutable:org.xrpl.rpc.v1.RawLedgerObject.predecessor)
  return _s;
}
inline const ::std::string& RawLedgerObject::_internal_predecessor() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.predecessor_.Get();
}
inline void RawLedgerObject::_internal_set_predecessor(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.predecessor_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RawLedgerObject::_internal_mutable_predecessor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.predecessor_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RawLedgerObject::release_predecessor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:org.xrpl.rpc.v1.RawLedgerObject.predecessor)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.predecessor_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.predecessor_.Set("", GetArena());
  }
  return released;
}
inline void RawLedgerObject::set_allocated_predecessor(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.predecessor_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.predecessor_.IsDefault()) {
    _impl_.predecessor_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:org.xrpl.rpc.v1.RawLedgerObject.predecessor)
}

// bytes successor = 5;
inline void RawLedgerObject::clear_successor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.successor_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& RawLedgerObject::successor() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.RawLedgerObject.successor)
  return _internal_successor();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void RawLedgerObject::set_successor(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.successor_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:org.xrpl.rpc.v1.RawLedgerObject.successor)
}
inline ::std::string* PROTOBUF_NONNULL RawLedgerObject::mutable_successor()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_successor();
  // @@protoc_insertion_point(field_mutable:org.xrpl.rpc.v1.RawLedgerObject.successor)
  return _s;
}
inline const ::std::string& RawLedgerObject::_internal_successor() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.successor_.Get();
}
inline void RawLedgerObject::_internal_set_successor(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.successor_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL RawLedgerObject::_internal_mutable_successor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.successor_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE RawLedgerObject::release_successor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:org.xrpl.rpc.v1.RawLedgerObject.successor)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.successor_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.successor_.Set("", GetArena());
  }
  return released;
}
inline void RawLedgerObject::set_allocated_successor(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.successor_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.successor_.IsDefault()) {
    _impl_.successor_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:org.xrpl.rpc.v1.RawLedgerObject.successor)
}

// -------------------------------------------------------------------

// RawLedgerObjects

// repeated .org.xrpl.rpc.v1.RawLedgerObject objects = 1;
inline int RawLedgerObjects::_internal_objects_size() const {
  return _internal_objects().size();
}
inline int RawLedgerObjects::objects_size() const {
  return _internal_objects_size();
}
inline void RawLedgerObjects::clear_objects() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.objects_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::org::xrpl::rpc::v1::RawLedgerObject* PROTOBUF_NONNULL RawLedgerObjects::mutable_objects(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:org.xrpl.rpc.v1.RawLedgerObjects.objects)
  return _internal_mutable_objects()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::org::xrpl::rpc::v1::RawLedgerObject>* PROTOBUF_NONNULL RawLedgerObjects::mutable_objects()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:org.xrpl.rpc.v1.RawLedgerObjects.objects)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_objects();
}
inline const ::org::xrpl::rpc::v1::RawLedgerObject& RawLedgerObjects::objects(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.RawLedgerObjects.objects)
  return _internal_objects().Get(index);
}
inline ::org::xrpl::rpc::v1::RawLedgerObject* PROTOBUF_NONNULL RawLedgerObjects::add_objects()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::org::xrpl::rpc::v1::RawLedgerObject* _add =
      _internal_mutable_objects()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:org.xrpl.rpc.v1.RawLedgerObjects.objects)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::org::xrpl::rpc::v1::RawLedgerObject>& RawLedgerObjects::objects() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:org.xrpl.rpc.v1.RawLedgerObjects.objects)
  return _internal_objects();
}
inline const ::google::protobuf::RepeatedPtrField<::org::xrpl::rpc::v1::RawLedgerObject>&
RawLedgerObjects::_internal_objects() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.objects_;
}
inline ::google::protobuf::RepeatedPtrField<::org::xrpl::rpc::v1::RawLedgerObject>* PROTOBUF_NONNULL
RawLedgerObjects::_internal_mutable_objects() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.objects_;
}

// -------------------------------------------------------------------

// BookSuccessor

// bytes book_base = 1;
inline void BookSuccessor::clear_book_base() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.book_base_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& BookSuccessor::book_base() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.BookSuccessor.book_base)
  return _internal_book_base();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void BookSuccessor::set_book_base(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.book_base_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:org.xrpl.rpc.v1.BookSuccessor.book_base)
}
inline ::std::string* PROTOBUF_NONNULL BookSuccessor::mutable_book_base()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_book_base();
  // @@protoc_insertion_point(field_mutable:org.xrpl.rpc.v1.BookSuccessor.book_base)
  return _s;
}
inline const ::std::string& BookSuccessor::_internal_book_base() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.book_base_.Get();
}
inline void BookSuccessor::_internal_set_book_base(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.book_base_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL BookSuccessor::_internal_mutable_book_base() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.book_base_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE BookSuccessor::release_book_base() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:org.xrpl.rpc.v1.BookSuccessor.book_base)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.book_base_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.book_base_.Set("", GetArena());
  }
  return released;
}
inline void BookSuccessor::set_allocated_book_base(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.book_base_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.book_base_.IsDefault()) {
    _impl_.book_base_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:org.xrpl.rpc.v1.BookSuccessor.book_base)
}

// bytes first_book = 2;
inline void BookSuccessor::clear_first_book() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.first_book_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& BookSuccessor::first_book() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:org.xrpl.rpc.v1.BookSuccessor.first_book)
  return _internal_first_book();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void BookSuccessor::set_first_book(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.first_book_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:org.xrpl.rpc.v1.BookSuccessor.first_book)
}
inline ::std::string* PROTOBUF_NONNULL BookSuccessor::mutable_first_book()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_first_book();
  // @@protoc_insertion_point(field_mutable:org.xrpl.rpc.v1.BookSuccessor.first_book)
  return _s;
}
inline const ::std::string& BookSuccessor::_internal_first_book() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.first_book_.Get();
}
inline void BookSuccessor::_internal_set_first_book(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.first_book_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL BookSuccessor::_internal_mutable_first_book() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.first_book_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE BookSuccessor::release_first_book() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:org.xrpl.rpc.v1.BookSuccessor.first_book)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.first_book_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.first_book_.Set("", GetArena());
  }
  return released;
}
inline void BookSuccessor::set_allocated_first_book(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.first_book_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.first_book_.IsDefault()) {
    _impl_.first_book_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:org.xrpl.rpc.v1.BookSuccessor.first_book)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace rpc
}  // namespace xrpl
}  // namespace org


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut>() {
  return ::org::xrpl::rpc::v1::LedgerSpecifier_Shortcut_descriptor();
}
template <>
struct is_proto_enum<::org::xrpl::rpc::v1::RawLedgerObject_ModificationType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::org::xrpl::rpc::v1::RawLedgerObject_ModificationType>() {
  return ::org::xrpl::rpc::v1::RawLedgerObject_ModificationType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // org_2fxrpl_2frpc_2fv1_2fledger_2eproto_2epb_2eh
