name: Generate build version number
description: "Generate build version number."

outputs:
  version:
    description: "The generated build version number."
    value: ${{ steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Generate version
      id: version
      shell: bash
      env:
        # When a tag is applied, the version is used as-is. When a tag is not
        # applied, then the version is extracted from the BuildInfo.cpp file and
        # the shortened commit hash appended to it.
        VERSION: ${{ github.event_name == 'tag' && github.ref_name || '' }}
      run: |
        if [[ -z "${VERSION}" ]]; then
          echo 'Extracting version from BuildInfo.cpp.'
          VERSION="$(cat src/libxrpl/protocol/BuildInfo.cpp | grep "versionString =" | awk -F '"' '{print $2}')"
          if [[ -z "${VERSION}" ]]; then
            echo 'Unable to extract version from BuildInfo.cpp.'
            exit 1
          fi

          echo 'Appending shortened commit hash to version.'
          VERSION="${VERSION}-${COMMIT_HASH:0:7}"
        fi
        echo "Generated version: ${VERSION}"

        echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"
