name: Generate build version number
description: "Generate build version number."

outputs:
  version:
    description: "The generated build version number."
    value: ${{ steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - name: Generate version
      id: version
      shell: bash
      env:
        # When a tag is applied, the version is used as-is. For all other cases,
        # a shortened commit hash is appended to the version.
        COMMIT_HASH: ${{ github.event_name == 'tag' && '' || github.sha }}
      run: |
        echo 'Extracting version from BuildInfo.cpp.'
        VERSION="$(cat src/libxrpl/protocol/BuildInfo.cpp | grep "versionString =" | awk -F '"' '{print $2}')"
        if [[ -z "${VERSION}" ]]; then
          echo 'Unable to extract version from BuildInfo.cpp.'
          exit 1
        fi

        if [[ -n "${COMMIT_HASH}" ]]; then
          echo 'Appending shortened commit hash to version.'
          VERSION="${VERSION}-${COMMIT_HASH:0:7}"
        fi

        echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"
