;; generated by wasm-tools print gc_test.wasm that has the following hex
;; 0061736d01000000010b026000017f5f027f017f0103020100070a010666696e69736800000a0a010800fb01011a41010b
(module
  (type (;0;) (func (result i32)))
  (type (;1;) (struct (field (mut i32)) (field (mut i32))))
  (export "finish" (func 0))
  (func (;0;) (type 0) (result i32)
    struct.new_default 1
    drop
    i32.const 1
  )
)
