# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu1404"
  config.vm.box_url = "https://github.com/kraksoft/vagrant-box-ubuntu/releases/download/14.04/ubuntu-14.04-amd64.box"

  config.vm.provision :shell, :inline => <<-EOT
     sudo sed -i '/LC_ALL=/d' /etc/default/locale
     echo 'LC_ALL="en_US.UTF-8"' |sudo tee -a /etc/default/locale
  EOT

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.customize ["modifyvm", :id, "--cpus", 1]
    # v.gui = true
  end

  config.vm.synced_folder "../..", "/src"

  $script = <<-SCRIPT
    #!/bin/bash
    apt-get update
    apt-get -y upgrade
    apt-get -y install git scons pkg-config protobuf-compiler libprotobuf-dev libssl-dev tmux
    apt-get install python-software-properties
    echo "deb [arch=amd64] http://mirrors.ripple.com/ubuntu/ trusty stable contrib" | tee /etc/apt/sources.list.d/ripple.list 
    wget -O- -q http://mirrors.ripple.com/mirrors.ripple.com.gpg.key | apt-key add -
    apt-get -y update
    apt-get install -y build-essential g++ python-dev autotools-dev libicu-dev build-essential libbz2-dev 
    apt-get install -y boost-all-dev
    cd /src/ && scons build/rippled
    cp /src/build/rippled /usr/local/sbin/rippled && strip /usr/local/sbin/rippled/rippled
    mkdir -p /etc/ripple/
    mkdir -p /home/vagrant/.config/ripple/
    cp /vagrant/rippled-example.cfg /home/vagrant/.config/ripple/rippled.cfg
    cp /vagrant/rippled-example.cfg /etc/ripple/rippled.cfg
    mkdir -p /root/.config/ripple/
    cp /vagrant/rippled-example.cfg /root/.config/ripple/rippled.cfg
    cp /vagrant/init.d_rippled /etc/init.d/rippled
    chmod +x /etc/init.d/rippled
    service rippled start
  SCRIPT

  config.vm.provision :shell, :inline => $script

  config.vm.define "one", primary: true do |one|
    one.vm.network "private_network", ip: "192.168.50.4"
    one.vm.network "forwarded_port", guest: 18080, host: 18080, auto_correct: true
    one.vm.provider :virtualbox do |vb|
      vb.memory = 4096
      vb.customize ["modifyvm", :id, "--cpus", 2]
    end
    $rippleclient = <<-SCRIPT
      #!/bin/bash

      sed -i '/ripple.com/d' /etc/hosts
      echo "127.0.0.1 local.ripple.com" | tee -a /etc/hosts
      echo "127.0.0.1 www.local.ripple.com" | tee -a /etc/hosts
      echo "127.0.0.1 ripple.local.ripple.com" | tee -a /etc/hosts

      echo "127.0.0.1 s-west.ripple.com" | tee -a /etc/hosts
      echo "127.0.0.1 s-east.ripple.com" | tee -a /etc/hosts
      echo "127.0.0.1 history.ripple.com" | tee -a /etc/hosts
      echo "127.0.0.1 api.ripplecharts.com" | tee -a /etc/hosts

      echo "127.0.0.1 id.ripple.com" | tee -a /etc/hosts
      echo "127.0.0.1 auth1.ripple.com" | tee -a /etc/hosts

      apt-get install nodejs npm -y
      rm -rf /usr/local/bin/node
      sudo ln -s /usr/bin/nodejs /usr/local/bin/node
      cd /
      git clone https://github.com/ripple/ripple-client.git
      cd ripple-client/
      git checkout d74f95d
      npm install -g grunt-cli
      npm install
      grunt
    SCRIPT

    config.vm.provision :shell, :inline => $rippleclient
  end

  config.vm.define "two", primary: true do |two|
    two.vm.network "private_network", ip: "192.168.50.5"
  end

  config.vm.define "tree", primary: true do |tree|
    tree.vm.network "private_network", ip: "192.168.50.6"
  end

  config.vm.define "four", primary: true do |four|
    four.vm.network "private_network", ip: "192.168.50.7"
  end

  config.vm.define "five", primary: true do |five|
    five.vm.network "private_network", ip: "192.168.50.8"
  end
end
