[package]
name = "xrpl-wasm-vm"
version = "0.1.0"
edition.workspace = true

[dependencies]
wasmi = { version = "2.0.0-beta.10", default-features = false, features = ["std", "validate", "portable-dispatch"] }
xrpl-host-functions = { path = "../xrpl-host-functions", features = ["wasmi_glue"] }

[dev-dependencies]
wat = "1"
