# The following variable is specific to this backend and its correct
# values might depend on your environment - feel free to set it accordingly.

ODBCINCLUDEDIR = -I/usr/include
ODBCLIBDIR = -L/usr/lib
ODBCLIBS = -lodbc -lodbcinst

# The rest of the Makefile is independent of the target environment.

COMPILER = g++
CXXFLAGS = -Wall -pedantic -Wno-long-long
INCLUDEDIRS = -I.. -I../../../core ${ODBCINCLUDEDIR}
LIBDIRS = -L.. -L../../../core ${ODBCLIBDIR}
LIBS = -lsoci_core -lsoci_odbc -ldl ${ODBCLIBS}  


test-odbc-mssql: test-odbc-mssql.cpp
	${COMPILER} -o $@ $? ${CXXFLAGS} ${INCLUDEDIRS} ${LIBDIRS} ${LIBS}

test-odbc-access: test-odbc-access.cpp
	${COMPILER} -o $@ $? ${CXXFLAGS} ${INCLUDEDIRS} ${LIBDIRS} ${LIBS}

clean :
	rm -f test-odbc-access.exe test-odbc-mssql.exe
