# The following variable is specific to this backend and its correct
# values might depend on your environment - feel free to set it accordingly.

PGSQLINCLUDEDIR = -I/usr/include
PGSQLLIBDIR = -L/usr/lib
PGSQLLIBS = -lpq

# The rest of the Makefile is indepentent of the target environment.

COMPILER = g++
CXXFLAGS = -Wall -pedantic -Wno-long-long
INCLUDEDIRS = -I.. -I../../../core/test -I../../../core ${PGSQLINCLUDEDIR}
LIBDIRS = -L.. -L../../../core ${PGSQLLIBDIR}
LIBS = -lsoci_core -lsoci_postgresql -ldl ${PGSQLLIBS}


test-postgresql : test-postgresql.cpp
	${COMPILER} -o $@ $? ${CXXFLAGS} ${INCLUDEDIRS} ${LIBDIRS} ${LIBS}


clean :
	rm -f test-postgresql
