//------------------------------------------------------------------------------
/*
    This file is part of Beast: https://github.com/vinniefalco/Beast
    Copyright 2013, Vinnie Falco <vinnie.falco@gmail.com>

    Permission to use, copy, modify, and/or distribute this software for any
    purpose  with  or without fee is hereby granted, provided that the above
    copyright notice and this permission notice appear in all copies.

    THE  SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
    WITH  REGARD  TO  THIS  SOFTWARE  INCLUDING  ALL  IMPLIED  WARRANTIES  OF
    MERCHANTABILITY  AND  FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
    ANY  SPECIAL ,  DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
    WHATSOEVER  RESULTING  FROM  LOSS  OF USE, DATA OR PROFITS, WHETHER IN AN
    ACTION  OF  CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

    Portions based on SOCI - The C++ Database Access Library: 

    SOCI: http://soci.sourceforge.net/

    This file incorporates work covered by the following copyright
    and permission notice:

    Copyright (C) 2004 Maciej Sobczak, Stephen Hutton, Mateusz Loskot,
    Pawel Aleksander Fedorynski, David Courtney, Rafal Bobrowski,
    Julian Taylor, Henning Basold, Ilia Barahovski, Denis Arnaud,
    Daniel Lidström, Matthieu Kermagoret, Artyom Beilis, Cory Bennett,
    Chris Weed, Michael Davidsaver, Jakub Stachowski, Alex Ott, Rainer Bauer,
    Martin Muenstermann, Philip Pemberton, Eli Green, Frederic Chateau,
    Artyom Tonkikh, Roger Orr, Robert Massaioli, Sergey Nikulov,
    Shridhar Daithankar, Sören Meyer-Eppler, Mario Valesco.

    Boost Software License - Version 1.0, August 17th, 2003

    Permission is hereby granted, free of charge, to any person or organization
    obtaining a copy of the software and accompanying documentation covered by
    this license (the "Software") to use, reproduce, display, distribute,
    execute, and transmit the Software, and to prepare derivative works of the
    Software, and to permit third-parties to whom the Software is furnished to
    do so, all subject to the following:

    The copyright notices in the Software and this entire statement, including
    the above license grant, this restriction and the following disclaimer,
    must be included in all copies of the Software, in whole or in part, and
    all derivative works of the Software, unless such copies or derivative
    works are solely in the form of machine-executable object code generated by
    a source language processor.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
    SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
    FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
    DEALINGS IN THE SOFTWARE.
*/
//==============================================================================

#ifndef BEAST_SQDB_DETAIL_USE_TYPE_H_INCLUDED
#define BEAST_SQDB_DETAIL_USE_TYPE_H_INCLUDED

namespace beast {
namespace sqdb {

namespace detail {

// base class for defining input data
class use_type_base
{
public:
    virtual ~use_type_base() {}
    virtual void bind(statement_imp& st, int& iParam) = 0;
    virtual void do_use() = 0;
    virtual void post_use() = 0;
    virtual void clean_up() = 0;
};

typedef type_ptr<use_type_base> use_type_ptr;

// handles builtin types
class standard_use_type : public use_type_base
{
public:
    standard_use_type(void* data, exchange_type type, bool bReadOnly)
        : m_data(data), m_type(type), m_ind(0), m_bReadOnly(bReadOnly) {}
    standard_use_type(void* data, exchange_type type, indicator& ind, bool bReadOnly)
        : m_data(data), m_type(type), m_ind(&ind), m_bReadOnly(bReadOnly) {}
    virtual ~standard_use_type();
    virtual void bind(statement_imp& st, int& iParam);
    virtual void do_use();
    virtual void post_use();
    virtual void clean_up();

    virtual void convert_to_base() {}
    virtual void convert_from_base() {}

private:
    void clean_up_backend();

private:
    void* m_data;
    exchange_type m_type;
    indicator* m_ind;
    bool m_bReadOnly;
    statement_imp* m_st;
    int m_iParam;
};

// worker for use
template<typename T>
class use_type : public standard_use_type
{
public:
    use_type(T& t)
        : standard_use_type(&t, static_cast<exchange_type>
                            (exchange_traits<T>::x_type), false) {}

    use_type(T const& t)
        : standard_use_type(const_cast<T*>(&t), static_cast<exchange_type>
                            (exchange_traits<T>::x_type), true) {}

    use_type(T& t, indicator& ind)
        : standard_use_type(&t, static_cast<exchange_type>
                            (exchange_traits<T>::x_type), ind, false) {}

    use_type(T const& t, indicator& ind)
        : standard_use_type(const_cast<T*>(&t), static_cast<exchange_type>
                            (exchange_traits<T>::x_type), ind, true) {}
};

// helpers for builtins
inline use_type_ptr do_use_null()
{
    return use_type_ptr(new standard_use_type(0, x_null, true));
}

template<typename T>
use_type_ptr do_use(T& t, basic_type_tag)
{
    return use_type_ptr(new use_type<T>(t));
}

template<typename T>
use_type_ptr do_use(T const& t, basic_type_tag)
{
    return use_type_ptr(new use_type<T>(t));
}

template<typename T>
use_type_ptr do_use(T& t, indicator& ind, basic_type_tag)
{
    return use_type_ptr(new use_type<T>(t, ind));
}

template<typename T>
use_type_ptr do_use(T const& t, indicator& ind, basic_type_tag)
{
    return use_type_ptr(new use_type<T>(t, ind));
}

} // detail

} // sqdb
} // beast

#endif
