ignorePaths:
    - external/**
    - build/**
    # TODO: go through test files too
    # For a first cut, just ignore everything in src/test
    - src/test/**
    - src/libxrpl/crypto
    - CMakeUserPresets.json
language: en
ignoreRegExpList:
    - /r[1-9A-HJ-NP-Za-km-z]{25,34}/g
    - /RIPPLE_[A-Z_]+_H_INCLUDED+/g
    - /RIPPLE_[A-Z_]+_H+/g
    - /boost::[a-z:]+/g
    - /std::[a-z:]+/g
    - /sle[a-z]{1,3}/g
    - /[a-z]{1,3}obj/g
    - /lib[a-z]+/g
    - /https?:\/\/[^\s"'<>]+/g
ignoreWords:
    - nudb
    - rippled
    - xrpl
    - rippletest
    - levelization
    - distro
    - xrplf
    - libpb
    - protos
    - protobuf
    - jemalloc
    - keylet
    - keylets
    - insuf
    - clawback
    - vfalco
    - funclets
    - shamap
    - rocksdb
    - noripple
    - mptoken
    - mptokens
    - nftoken
    - nftokens
    - mptid
    - mptokenid
    - nftid
    - nftokenid
    - permissioned
    - variadics
    - jlog
    - daria
    - checkme
    - xchain
    - insuff
    - preauth
    - preauthorization
    - preauthorize
    - libxrpl
    - legleux
    - sle
    - sles
    - txs
    - tx
    - txid
    - txids
    - txjson
    - txn
    - txns
    - deserializaton
    - ledgerhash
    - ledgerindex
    - wptr
    - replayer
    - cowid
    - xrpld
    - conanrun
    - bindir
    - ters
    - RIPD
    - USDB
    - RLUSD
    - ters
    - AMMID
    - takerpays
    - takergets
    - autobridged
    - autobridge
    - autobridging
    - mptissuance
    - preclaim
    - finalizers
    - LOCALGOOD
    - SIGGOOD
    - compr
    - shamapitem
    - ptrs
    - Merkle
    - nullptr
    - ctid
    - nftoffer
    - ledgerentry
    - hotwallet
    - coldwallet
    - venv
    - pyenv
    - gcov
    - inequation
    - levelized
    - vinnie
    - falco
    - fmtdur
    - ifndef
    - nunl
    - sidechain
    - nftpage
    - cryptocondition
    - cryptoconditions
    - preauthorizes
    - coro
    - unshareable
    - chrono
    - sttx
    - stobj
    - queuable
    - multisigned
    - multisign
    - multisig
    - nikb
    - rngfill
    - paychan
    - perminute
    - ious
    - iou
    - stpath
    - stpathset
    - amt
    - amts
    - xxhasher
    - bookdir
    - ripplerpc
    - mptflags
    - mptbalance
    - permdex
    - ostr
    - soci
    - unshares
    - lseq
    - secp
    - superpeer
    - superpeers
    - nftokenpages
