ignorePaths:
  - build/**
  - src/libxrpl/crypto
  - src/test/** # Will be removed in the future
  - CMakeUserPresets.json
  - Doxyfile
  - docs/**/*.puml
  - cmake/**
  - LICENSE.md
language: en
allowCompoundWords: true
ignoreRandomStrings: true
minWordLength: 5
dictionaries:
  - cpp
  - en_US
  - en_GB
ignoreRegExpList:
  - /[rs][1-9A-HJ-NP-Za-km-z]{25,34}/g # addresses and seeds
  - /(XRPL|BEAST)_[A-Z_0-9]+_H_INCLUDED+/g # include guards
  - /(XRPL|BEAST)_[A-Z_0-9]+_H+/g # include guards
  - /::[a-z:_]+/g # things from other namespaces
  - /lib[a-z]+/g # libraries
  - /[0-9]{4}-[0-9]{2}-[0-9]{2}[,:][A-Za-zÀ-ÖØ-öø-ÿ.\s]+/g # copyright dates
  - /[0-9]{4}[,:]?\s*[A-Za-zÀ-ÖØ-öø-ÿ.\s]+/g # copyright years
  - /\[[A-Za-z0-9-]+\]\(https:\/\/github.com\/[A-Za-z0-9-]+\)/g # Github usernames
  - /-[DWw][a-zA-Z0-9_-]+=/g # compile flags
  - /[\['"`]-[DWw][a-zA-Z0-9_-]+['"`\]]/g # compile flags
suggestWords:
  - xprl->xrpl
  - unsynched->unsynced
  - synched->synced
  - synch->sync
words:
  - abempty
  - AMMID
  - amt
  - amts
  - asnode
  - asynchrony
  - attestation
  - authorises
  - autobridge
  - autobridged
  - autobridging
  - bimap
  - bindir
  - bookdir
  - Bougalis
  - Britto
  - Btrfs
  - canonicality
  - checkme
  - chrono
  - citardauq
  - clawback
  - clawbacks
  - coeffs
  - coldwallet
  - compr
  - conanfile
  - conanrun
  - connectability
  - coro
  - coros
  - cowid
  - cryptocondition
  - cryptoconditional
  - cryptoconditions
  - csprng
  - ctid
  - currenttxhash
  - daria
  - dcmake
  - dearmor
  - deleteme
  - demultiplexer
  - deserializaton
  - desync
  - desynced
  - determ
  - distro
  - doxyfile
  - dxrpl
  - endmacro
  - exceptioned
  - Falco
  - finalizers
  - firewalled
  - fmtdur
  - funclets
  - gcov
  - gcovr
  - ghead
  - Gnutella
  - gpgcheck
  - gpgkey
  - hotwallet
  - ifndef
  - inequation
  - insuf
  - insuff
  - iou
  - ious
  - isrdc
  - jemalloc
  - jlog
  - keylet
  - keylets
  - keyvadb
  - ledgerentry
  - ledgerhash
  - ledgerindex
  - leftw
  - legleux
  - levelization
  - levelized
  - libpb
  - libxrpl
  - llection
  - LOCALGOOD
  - logwstream
  - lseq
  - lsmf
  - ltype
  - MEMORYSTATUSEX
  - Merkle
  - Metafuncton
  - misprediction
  - mptbalance
  - mptflags
  - mptid
  - mptissuance
  - mptissuanceid
  - mptoken
  - mptokenid
  - mptokenissuance
  - mptokens
  - mpts
  - multisig
  - multisign
  - multisigned
  - Nakamoto
  - nftid
  - nftoffer
  - nftoken
  - nftokenid
  - nftokenpages
  - nftokens
  - nftpage
  - nikb
  - nonxrp
  - noripple
  - nudb
  - nullptr
  - nunl
  - Nyffenegger
  - ostr
  - partitioner
  - paychan
  - paychans
  - permdex
  - perminute
  - permissioned
  - pointee
  - preauth
  - preauthorization
  - preauthorize
  - preauthorizes
  - preclaim
  - protobuf
  - protos
  - ptrs
  - pyenv
  - qalloc
  - queuable
  - Raphson
  - replayer
  - rerere
  - retriable
  - RIPD
  - ripdtop
  - rippleci
  - rippled
  - ripplerpc
  - rippletest
  - RLUSD
  - rngfill
  - rocksdb
  - Rohrs
  - roundings
  - sahyadri
  - Satoshi
  - secp
  - sendq
  - seqit
  - sf
  - shamap
  - shamapitem
  - sidechain
  - SIGGOOD
  - sle
  - sles
  - soci
  - socidb
  - sslws
  - statsd
  - STATSDCOLLECTOR
  - stissue
  - stnum
  - stobj
  - stobject
  - stpath
  - stpathset
  - sttx
  - stvar
  - stvector
  - stxchainattestations
  - superpeer
  - superpeers
  - takergets
  - takerpays
  - ters
  - TMEndpointv2
  - trixie
  - tx
  - txid
  - txids
  - txjson
  - txn
  - txns
  - txs
  - umant
  - unacquired
  - unambiguity
  - unauthorizes
  - unauthorizing
  - unergonomic
  - unfetched
  - unflatten
  - unfund
  - unimpair
  - unroutable
  - unscalable
  - unserviced
  - unshareable
  - unshares
  - unsquelch
  - unsquelched
  - unsquelching
  - unvalidated
  - unveto
  - unvetoed
  - upvotes
  - USDB
  - variadics
  - venv
  - vfalco
  - vinnie
  - wasmi
  - wextra
  - wptr
  - writeme
  - wsrch
  - wthread
  - xbridge
  - xchain
  - ximinez
  - XMACRO
  - xrpkuwait
  - xrpl
  - xrpld
  - xrplf
  - xxhash
  - xxhasher
