#pragma once

#include <xrpl/beast/unit_test.h>

#include <lean/lean.h>

#include <cstdint>
#include <functional>
#include <mutex>
#include <random>
#include <string_view>

// Generated by Lean. Starts the Lean runtime, called once.
extern "C" void
lean_initialize_runtime_module(void);

// Generated by Lean, one initializer per module, named initialize_<package>_<module path>.
// It first initializes every imported module, so this one root covers the whole model.
extern "C" lean_object*
initialize_XRPL_XRPL_FFI_FFI(uint8_t builtin, lean_object* w);

namespace xrpl::test::formal_verification {

// Per-thread RNG; beginCase reseeds it deterministically per case.
inline std::mt19937_64&
nextRng()
{
    thread_local std::mt19937_64 rng{0xBEEFCAFEDEADBEEFULL};
    return rng;
}

// Base class for all Lean FFI test suites. Lean's runtime is single threaded,
// so run() initializes it once and holds a lock for the whole suite.
class LeanSuite : public beast::unit_test::Suite
{
    static std::mutex&
    leanMutex()
    {
        static std::mutex m;
        return m;
    }

    // Initializes the Lean runtime and the FFI module once per process.
    // Returns false if that failed. Every suite then fails fast in run().
    static bool
    ensureLeanInit()
    {
        static std::once_flag flag;
        static bool ok = false;
        std::call_once(flag, [] {
            lean_initialize_runtime_module();
            lean_object* res = initialize_XRPL_XRPL_FFI_FFI(1, lean_io_mk_world());
            if (!lean_io_result_is_ok(res))
            {
                lean_dec(res);
                return;
            }
            lean_dec_ref(res);
            lean_io_mark_end_initialization();
            ok = true;
        });
        return ok;
    }

    // Test body of a derived suite. Runs with the Lean lock held.
    virtual void
    runTests() = 0;

protected:
    // Pass "Suite.method" for seedRng so the per-thread RNG seed is unique
    // across suites that share method names.
    void
    beginCase(char const* name, bool seedRng = false)
    {
        testcase << name;
        if (seedRng)
            nextRng().seed(std::hash<std::string_view>{}(name));
    }

    // Runs a randomized check many times. Pass/fail is recorded inside the check.
    template <typename F>
    void
    runFuzz(int iterations, F&& check)
    {
        for (int i = 0; i < iterations; ++i)
            (void)check();
    }

public:
    void
    run() final
    {
        std::lock_guard<std::mutex> lock(leanMutex());
        if (!ensureLeanInit())
        {
            fail("Lean runtime failed to initialize");
            return;
        }
        runTests();
    }
};

}  // namespace xrpl::test::formal_verification
