
// Versions

#ifndef SERVER_VERSION_MAJ

#define SERVER_VERSION_MAJ	0
#define SERVER_VERSION_MIN	2
#define SERVER_VERSION_SUB	"-a"
#define SERVER_NAME			"NewCoin"

#define SV_STRINGIZE(x)		SV_STRINGIZE2(x)
#define SV_STRINGIZE2(x)	#x
#define SERVER_VERSION		\
	(SERVER_NAME "-" SV_STRINGIZE(SERVER_VERSION_MAJ) "." SV_STRINGIZE(SERVER_VERSION_MIN) SERVER_VERSION_SUB)

#define PROTO_VERSION_MAJ	0
#define PROTO_VERSION_MIN	1

#define MIN_PROTO_MAJ		0
#define MIN_PROTO_MIN		1

#endif
