name = "XRPL"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["XRPL"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[lean_lib]]
name = "XRPL"

# lake build XRPLModel:static
[[lean_lib]]
name = "XRPLModel"
roots = ["XRPL.Model.Model", "XRPL.FFI.FFI"]
globs = ["XRPL.Model.+", "XRPL.FFI.+"]
