name: dependencies
inputs:
  profile:
    required: false
  conf:
    required: false
  compiler:
    required: true
  compiler_version:
    required: true
  configuration:
    required: true
# An implicit input is the environment variable `build_dir`.
runs:
  using: composite
  steps:
    - name: export custom recipes
      shell: bash
      run: |
        conan export --version 1.1.10 external/snappy
        conan export --version 9.7.3 external/rocksdb
        conan export --version 4.0.3 external/soci
        conan export --version 2.0.8 external/nudb
    - name: add Ripple Conan remote
      shell: bash
      run: |
        conan remote add ripple --index 0 ${{ env.CONAN_URL }} --force
        conan remote list
    - name: install dependencies
      shell: bash
      run: |
        conf_args=()
        while read -r line; do
          [[ -n "$line" ]] && conf_args+=("--conf" "$line")
        done <<< "${{ inputs.conf }}"
        conan profile show --profile:all "${{ inputs.profile }}"
        echo "Running Conan install with conf: ${conf_args[*]}"
        echo "and profile: ${{ inputs.profile }}"
        conan install . \
          --profile:all "${{ inputs.profile }}" \
          --output-folder "${build_dir}" \
          --build missing \
          "${conf_args[@]}"
      # run: >-
      #   conan install .
      #   --profile:a ${{ inputs.profile }}
      #   --output-folder "${build_dir}"
      #   --build missing
