name: dependencies
inputs:
  configuration:
    required: true
# Implicit inputs are the environment variables `build_dir`, CONAN_REMOTE_URL,
# CONAN_REMOTE_USERNAME, and CONAN_REMOTE_PASSWORD. The latter two are only
# used to upload newly built dependencies to the Conan remote.
runs:
  using: composite
  steps:
    - name: add Conan remote
      if: ${{ env.CONAN_REMOTE_URL != '' }}
      shell: bash
      run: |
        echo "Adding Conan remote 'xrplf' at ${{ env.CONAN_REMOTE_URL }}."
        conan remote add --index 0 --force xrplf ${{ env.CONAN_REMOTE_URL }}
        echo "Listing Conan remotes."
        conan remote list
    - name: install dependencies
      shell: bash
      run: |
        mkdir ${{ env.build_dir }}
        cd ${{ env.build_dir }}
        conan install \
          --output-folder . \
          --build missing \
          --options:host "&:tests=True" \
          --options:host "&:xrpld=True" \
          --settings:all build_type=${{ inputs.configuration }} \
          ..
    - name: upload dependencies
      if: ${{ env.CONAN_REMOTE_URL != '' && env.CONAN_REMOTE_USERNAME != '' && env.CONAN_REMOTE_PASSWORD != '' && github.ref_type == 'branch' && github.ref_name == github.event.repository.default_branch }}
      shell: bash
      run: |
        echo "Logging into Conan remote 'xrplf' at ${{ env.CONAN_REMOTE_URL }}."
        conan remote login xrplf "${{ env.CONAN_REMOTE_USERNAME }}" --password "${{ env.CONAN_REMOTE_PASSWORD }}"
        echo "Uploading dependencies."
        conan upload '*' --confirm --check --remote xrplf
