name: dependencies
inputs:
  configuration:
    required: true
# An implicit input is the environment variable `build_dir`.
runs:
  using: composite
  steps:
    - name: unlock Conan
      shell: bash
      run: conan remove --locks
    - name: export custom recipes
      shell: bash
      run: |
        conan export external/snappy snappy/1.1.10@
        conan export external/soci soci/4.0.3@
    - name: install dependencies
      shell: bash
      run: |
        # Ensure the build_dir does not exist. This should only happen if
        # actions/build is called in the same job as actions/dependencies
        rm -rf ${build_dir}
        mkdir ${build_dir}
        cd ${build_dir}
        conan install \
          --output-folder . \
          --build missing \
          --settings build_type=${{ inputs.configuration }} \
          ..
