name: dependencies
inputs:
  configuration:
    required: true
# An implicit input is the environment variable `build_dir`.
runs:
  using: composite
  steps:
    - name: unlock Conan
      shell: bash
      run: conan remove --locks
    - name: export custom recipes
      shell: bash
      run: |
        conan config set general.revisions_enabled=1
        conan export external/snappy snappy/1.1.10@
        conan export external/rocksdb rocksdb/6.29.5@
        conan export external/soci soci/4.0.3@
    - name: install dependencies
      shell: bash
      run: |
        mkdir ${build_dir}
        cd ${build_dir}
        conan install \
          --output-folder . \
          --build missing \
          --settings build_type=${{ inputs.configuration }} \
          ..
