name: dependencies
inputs:
  compiler:
    required: false
  compiler_version:
    required: false
  configuration:
    required: false
  conf:
    required: false
# An implicit input is the environment variable `build_dir`.
runs:
  using: composite
  steps:
    - name: install dependencies
      shell: bash
      run: |
        conf_args=()
        while read -r line; do
          [[ -n "$line" ]] && conf_args+=("--conf" "$line")
        done <<< "${{ inputs.conf }}"
        echo "building with config: ${{inputs.configuration }}"
        conan install . \
          -s:a build_type=${{ inputs.configuration }} \
          --output-folder "${build_dir}" \
          --build missing \
          "${conf_args[@]}"
