# This workflow builds and tests the binary for various configurations.
name: Build and test

# This workflow can only be triggered by other workflows.
on:
  workflow_call:
    inputs:
      build_dir:
        description: 'The directory where to build.'
        required: false
        type: string
        default: '.build'
      conan_remote_name:
        description: 'The name of the Conan remote to use.'
        required: true
        type: string
      conan_remote_url:
        description: 'The URL of the Conan endpoint to use.'
        required: true
        type: string
      dependencies_force_build:
        description: 'Force building of all dependencies.'
        required: false
        type: boolean
        default: false
      dependencies_force_upload:
        description: 'Force uploading of all dependencies.'
        required: false
        type: boolean
        default: false
      os:
        description: 'The operating system to use for the build (linux, macos, or windows).'
        required: true
        type: string
    secrets:
      codecov_token:
        description: 'The Codecov token to use for uploading coverage reports.'
        required: false
      conan_remote_username:
        description: 'The username for logging into the Conan remote. If not provided, the dependencies will not be uploaded.'
        required: false
      conan_remote_password:
        description: 'The password for logging into the Conan remote. If not provided, the dependencies will not be uploaded.'
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.os }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  # Global configuration for Conan. This is used to set the number of parallel
  # downloads, uploads, and build jobs. The verbosity is set to verbose to
  # provide more information during the build process.
  CONAN_GLOBAL_CONF: |
    core:non_interactive=True
    core.download:parallel={{ os.cpu_count() }}
    core.upload:parallel={{ os.cpu_count() }}
    tools.build:jobs={{ (os.cpu_count() * 4/5) | int }}
    tools.build:verbosity=verbose
    tools.compilation:verbosity=verbose

jobs:
  # Generate the strategy matrix to be used by the following job.
  generate-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.13
      - name: Generate strategy matrix
        working-directory: .github/scripts/strategy-matrix
        id: generate
        run: python generate.py --config=${{ inputs.os }}.json --ref=${{ github.ref }} >> "${GITHUB_OUTPUT}"
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

  # Build and test the binary.
  build-test:
    needs:
      - generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.architecture.runner }}
    container: ${{ inputs.os == 'linux' && format('ghcr.io/xrplf/ci/{0}-{1}:{2}-{3}', matrix.os.distro_name, matrix.os.distro_version, matrix.os.compiler_name, matrix.os.compiler_version) || null }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Set up Python
        if: ${{ inputs.os == 'windows' }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.13
      - name: Install Conan
        if: ${{ inputs.os == 'windows' }}
        run: pip install wheel conan
      - name: Check configuration
        if: ${{ inputs.os == 'windows' }}
        run: |
          echo "Checking environment variables."
          set

          echo "Checking CMake version."
          cmake --version

          echo "Checking Conan version."
          conan --version
      - name: Check configuration
        if: ${{ inputs.os == 'linux' || inputs.os == 'macos' }}
        run: |
          echo "Checking path"
          echo ${PATH} | tr ':' '\n'

          echo "Checking environment variables."
          env | sort

          echo "Checking CMake version."
          cmake --version

          echo "Checking compiler version."
          ${{ inputs.os == 'linux' && '${CC}' || 'clang' }} --version

          echo "Checking Conan version."
          conan --version

          echo "Checking Ninja version."
          ninja --version
      - name: Build dependencies
        uses: ./.github/actions/build-deps
        with:
          build_dir: ${{ inputs.build_dir }}
          build_type: ${{ matrix.build_type }}
          conan_global_conf: ${{ env.CONAN_GLOBAL_CONF }}
          conan_remote_name: ${{ inputs.conan_remote_name }}
          conan_remote_url: ${{ inputs.conan_remote_url }}
          conan_remote_username: ${{ secrets.conan_remote_username }}
          conan_remote_password: ${{ secrets.conan_remote_password }}
          config_name: ${{ matrix.config_name }}
          force_build: ${{ inputs.dependencies_force_build }}
          force_upload: ${{ inputs.dependencies_force_upload }}
          os: ${{ inputs.os }}
      - name: Build and test binary
        uses: ./.github/actions/build-test
        with:
          build_dir: ${{ inputs.build_dir }}
          build_type: ${{ matrix.build_type }}
          cmake_args: ${{ matrix.cmake_args }}
          cmake_target: ${{ matrix.cmake_target }}
          codecov_token: ${{ secrets.codecov_token }}
          os: ${{ inputs.os }}
