# This workflow builds and tests the binary for various MacOS configurations.
name: Build and test on MacOS

# This workflow can only be triggered by other workflows.
on:
  workflow_call:
    inputs:
      build_dir:
        description: 'The directory where to build.'
        required: false
        type: string
        default: '.build'
      dependencies_force_build:
        description: 'Force building of all dependencies.'
        required: false
        type: boolean
        default: false
      dependencies_force_upload:
        description: 'Force uploading of all dependencies.'
        required: false
        type: boolean
        default: false
    secrets:
      conan_remote_username:
        description: 'The username for logging into the Conan remote. If not provided, the dependencies will not be uploaded.'
        required: false
      conan_remote_password:
        description: 'The password for logging into the Conan remote. If not provided, the dependencies will not be uploaded.'
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-macos
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  # Global configuration for Conan. This is used to set the number of parallel
  # downloads, uploads, and build jobs. The verbosity is set to verbose to
  # provide more information during the build process.
  CONAN_GLOBAL_CONF: |
    core:non_interactive=True
    core.download:parallel={{ os.cpu_count() }}
    core.upload:parallel={{ os.cpu_count() }}
    tools.build:jobs={{ (os.cpu_count() * 4/5) | int }}
    tools.build:verbosity=verbose
    tools.compilation:verbosity=verbose

jobs:
  # Generate the strategy matrix to be used by the following job.
  generate-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.13
      - name: Generate strategy matrix
        working-directory: .github/scripts/strategy-matrix
        id: generate
        run: python generate.py --config=macos.json --ref=${{ github.ref }} >> "${GITHUB_OUTPUT}"
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}

  # Build and test the binary.
  build-test:
    needs:
      - generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.architecture.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Check configuration
        run: |
          echo "Checking path"
          echo ${PATH} | tr ':' '\n'

          echo "Checking environment variables."
          env | sort

          echo "Checking CMake version."
          cmake --version

          echo "Checking compiler version."
          clang --version

          echo "Checking Conan version."
          conan --version

          echo "Checking Ninja version."
          ninja --version
      - name: Build dependencies
        uses: ./.github/actions/build-deps
        with:
          build_dir: ${{ inputs.build_dir }}
          build_type: ${{ matrix.build_type }}
          conan_global_conf: ${{ env.CONAN_GLOBAL_CONF }}
          conan_remote_username: ${{ secrets.conan_remote_username }}
          conan_remote_password: ${{ secrets.conan_remote_password }}
          config_name: ${{ matrix.config_name }}
          force_build: ${{ inputs.dependencies_force_build }}
          force_upload: ${{ inputs.dependencies_force_upload }}
          os: 'MacOS'
      - name: Build and test binary
        uses: ./.github/actions/build-test
        with:
          build_dir: ${{ inputs.build_dir }}
          build_type: ${{ matrix.build_type }}
          cmake_args: ${{ matrix.cmake_args }}
          cmake_generator: 'Ninja'
          cmake_target: ${{ matrix.cmake_target }}
          os: 'MacOS'
