name: Check PR title

on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]
    branches: [develop]

jobs:
  check_title:
    if: ${{ github.event.pull_request.draft != true }}
    uses: XRPLF/actions/.github/workflows/check-pr-title.yml@a5d8dd35be543365e90a11358447130c8763871d
