name: Check PR commits

on:
  pull_request_target:

# The action needs to have write permissions to post comments on the PR.
permissions:
  contents: read
  pull-requests: write

jobs:
  check_commits:
    uses: XRPLF/actions/.github/workflows/check-pr-commits.yml@d7c65e49225a38f6d8010eacf017bb5a98d7476c
