name: Check PR title

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [develop]

jobs:
  check_title:
    uses: XRPLF/actions/.github/workflows/check-pr-title.yml@943eb8277e8f4b010fde0c826ce4154c36c39509
