name: Check PR description

on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - develop
      - "release-*"
      - "release/*"
      - "staging/*"

jobs:
  check_description:
    if: ${{ github.event.pull_request.draft != true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Write PR body to file
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        if: ${{ github.event_name == 'pull_request' }}
        run: printenv PR_BODY >pr_body.md

      - name: Check PR description differs from template
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          python .github/scripts/check-pr-description.py \
              --template-file .github/pull_request_template.md \
              --pr-body-file pr_body.md
