name: Check libXRPL compatibility with Clio
env:
  CONAN_URL: http://18.143.149.228:8081/artifactory/api/conan/dev
  CONAN_LOGIN_USERNAME_RIPPLE: ${{ secrets.CONAN_USERNAME }}
  CONAN_PASSWORD_RIPPLE: ${{ secrets.CONAN_TOKEN }}
on:
  pull_request:
    paths:
      - 'src/libxrpl/protocol/BuildInfo.cpp'
      - '.github/workflows/libxrpl.yml'
    types: [opened, reopened, synchronize, ready_for_review]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    if: ${{ github.event_name == 'push' || github.event.pull_request.draft != true || contains(github.event.pull_request.labels.*.name, 'DraftRunCI') }}
    name: Publish libXRPL
    outputs:
      outcome: ${{ steps.upload.outputs.outcome }}
      version: ${{ steps.version.outputs.version }}
      channel: ${{ steps.channel.outputs.channel }}
    runs-on: [self-hosted, heavy]
    container: ghcr.io/xrplf/ci/ubuntu-jammy:gcc-12

    steps:
      - name: Wait for essential checks to succeed
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          running-workflow-name: wait-for-check-regexp
          check-regexp: '(dependencies|test).*linux.*' # Ignore windows and mac tests but make sure linux passes
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set clio
        id: pr_number
        shell: bash
        run: |
          echo pr_number="clio_pr_${{ github.event.pull_request.number }}" | tee ${GITHUB_OUTPUT}
      - name: Export new package
        shell: bash
        run: |
          conan export . --version ${{ steps.pr_number.outputs.pr_number }}
      - name: Add Ripple Conan remote
        shell: bash
        run: |
          if conan remote list | grep -q "ripple"; then
              conan remote remove ripple
              echo "Removed conan remote ripple"
          fi
          conan remote add --index 0 ripple "${CONAN_URL}"
          echo "Added conan remote ripple at ${CONAN_URL}"

      - name: Parse new version
        id: xrpl_version
        shell: bash
        run: |
          echo xrpl_version="$(cat src/libxrpl/protocol/BuildInfo.cpp | grep "versionString =" \
            | awk -F '"' '{print $2}')" | tee ${GITHUB_OUTPUT}
      - name: Try to authenticate to Ripple Conan remote
        id: remote
        if: env.CONAN_LOGIN_USERNAME_RIPPLE != '' && env.CONAN_PASSWORD_RIPPLE != ''
        shell: bash
        run: |
          echo "Authenticating to ripple remote..."
          conan remote auth ripple --force
          conan remote list-users
      - name: Upload new package
        id: upload
        if: (steps.remote.outputs.outcome == 'success')
        shell: bash
        run: |
          ver="${{ steps.xrpl_version.outputs.xrpl_version }}+${{ steps.pr_number.outputs.pr_number }}"
          echo "conan upload xrpl${ver}"
          echo outcome=$(conan upload xrpl/${ver} --remote ripple --confirm >&2 \
            && echo success || echo failure) | tee ${GITHUB_OUTPUT}
  notify_clio:
    name: Notify Clio
    runs-on: ubuntu-latest
    needs: publish
    env:
      GH_TOKEN: ${{ secrets.CLIO_NOTIFY_TOKEN }}
    steps:
      - name: Notify Clio about new version
        if: (needs.publish.outputs.outcome == 'success')
        shell: bash
        run: |
          gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/xrplf/clio/dispatches -f "event_type=check_libxrpl" \
          -F "client_payload[version]=${{ needs.publish.outputs.xrpl_version }}" \
          -F "client_payload[pr]=${{ github.event.pull_request.number }}"
