# This workflow runs all workflows to check, build and test the project on
# various Linux flavors, as well as on MacOS and Windows, on every push to a
# user branch. However, it will not run if the pull request is a draft unless it
# has the 'DraftRunCI' label.
name: PR

on:
  push:
    branches-ignore:
      - develop
      - release
      - master
    paths:
      - '.github/actions/build-deps/**'
      - '.github/actions/build-test/**'
      - '.github/scripts/levelization/**'
      - '.github/scripts/strategy-matrix/**'
      - '.github/workflows/build-linux.yml'
      - '.github/workflows/build-macos.yml'
      - '.github/workflows/build-windows.yml'
      - '.github/workflows/check-clang-format.yml'
      - '.github/workflows/check-levelization.yml'
      - '.github/workflows/notify-clio.yml'
      - 'on-pr.yml'
      # Keep the list of paths below in sync with those in `on-trigger.yml`.
      - 'cmake/**'
      - 'conan/**'
      - 'external/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - '.clang-format'
      - '.codecov.yml'
      - '.pre-commit-config.yaml'
      - 'CMakeLists.txt'
      - 'conanfile.py'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check-clang-format:
    if: ${{ github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'DraftRunCI') }}
    uses: ./.github/workflows/check-clang-format.yml

  check-levelization:
    if: ${{ github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'DraftRunCI') }}
    uses: ./.github/workflows/check-levelization.yml

  build-linux:
    if: ${{ github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'DraftRunCI') }}
    uses: ./.github/workflows/build-linux.yml
    with:
      conan_remote_name: ${{ vars.CONAN_REMOTE_NAME }}
      conan_remote_url: ${{ vars.CONAN_REMOTE_URL }}

  build-macos:
    if: ${{ github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'DraftRunCI') }}
    uses: ./.github/workflows/build-macos.yml
    with:
      conan_remote_name: ${{ vars.CONAN_REMOTE_NAME }}
      conan_remote_url: ${{ vars.CONAN_REMOTE_URL }}

  build-windows:
    if: ${{ github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'DraftRunCI') }}
    uses: ./.github/workflows/build-windows.yml
    with:
      conan_remote_name: ${{ vars.CONAN_REMOTE_NAME }}
      conan_remote_url: ${{ vars.CONAN_REMOTE_URL }}

  notify-clio:
    needs:
      - build-linux
      - build-macos
      - build-windows
    uses: ./.github/workflows/notify-clio.yml
    with:
      conan_remote_name: ${{ vars.CONAN_REMOTE_NAME }}
      conan_remote_url: ${{ vars.CONAN_REMOTE_URL }}
    secrets:
      clio_notify_token: ${{ secrets.CLIO_NOTIFY_TOKEN }}
      conan_remote_username: ${{ secrets.CONAN_REMOTE_USERNAME }}
      conan_remote_password: ${{ secrets.CONAN_REMOTE_PASSWORD }}
