# This workflow runs all workflows to check, build and test the project on
# various Linux flavors, as well as MacOS and Windows.
name: Push

# This workflow is triggered on every push to the repository, including pull
# requests. However, it will not run if the pull request is a draft unless it
# has the 'DraftRunCI' label. The missing commits check is only run when the
# code is merged into the 'develop' or 'release' branches, and the documentation
# is built when the code is merged into the 'develop' branch.
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check-clang-format:
    if: ${{ github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'DraftRunCI') }}
    uses: ./.github/workflows/check-clang-format.yml

  check-levelization:
    if: ${{ github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'DraftRunCI') }}
    uses: ./.github/workflows/check-levelization.yml

  check-missing-commits:
    if: ${{ github.ref_type == 'branch' && contains(fromJSON('["develop", "release"]'), github.ref_name) }}
    uses: ./.github/workflows/check-missing-commits.yml

  build-linux:
    if: ${{ github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'DraftRunCI') }}
    uses: ./.github/workflows/build-linux.yml
    with:
      conan_remote_name: ${{ vars.CONAN_REMOTE_NAME }}
      conan_remote_url: ${{ vars.CONAN_REMOTE_URL }}

  build-macos:
    if: ${{ github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'DraftRunCI') }}
    uses: ./.github/workflows/build-macos.yml
    with:
      conan_remote_name: ${{ vars.CONAN_REMOTE_NAME }}
      conan_remote_url: ${{ vars.CONAN_REMOTE_URL }}

  build-windows:
    if: ${{ github.event.pull_request.draft == false || contains(github.event.pull_request.labels.*.name, 'DraftRunCI') }}
    uses: ./.github/workflows/build-windows.yml
    with:
      conan_remote_name: ${{ vars.CONAN_REMOTE_NAME }}
      conan_remote_url: ${{ vars.CONAN_REMOTE_URL }}

  publish-clio:
    needs:
      - build-linux
      - build-macos
      - build-windows
    uses: ./.github/workflows/publish-clio.yml
    with:
      conan_remote_name: ${{ vars.CONAN_REMOTE_NAME }}
      conan_remote_url: ${{ vars.CONAN_REMOTE_URL }}
    secrets:
      clio_notify_token: ${{ secrets.CLIO_NOTIFY_TOKEN }}
      conan_remote_username: ${{ secrets.CONAN_REMOTE_USERNAME }}
      conan_remote_password: ${{ secrets.CONAN_REMOTE_PASSWORD }}

  publish-docs:
    needs:
      - build-linux
      - build-macos
      - build-windows
    if: ${{ github.ref_type == 'branch' && github.ref_name == github.event.repository.default_branch }}
    uses: ./.github/workflows/publish-docs.yml

