# When a versioned tag is pushed, this workflow:
#
#   - uploads the libxrpl recipe to the Conan remote
#   - builds and tests the release binaries
#   - builds the DEB and RPM packages
#   - publishes those packages to the XRPLF package repositories
name: Tag

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  upload-recipe:
    if: ${{ github.repository == 'XRPLF/rippled' }}
    uses: ./.github/workflows/reusable-upload-recipe.yml
    secrets:
      remote_username: ${{ secrets.NEXUS_REMOTE_USERNAME }}
      remote_password: ${{ secrets.NEXUS_REMOTE_PASSWORD }}

  build-test:
    if: ${{ github.repository_owner == 'XRPLF' }}
    uses: ./.github/workflows/reusable-build-test.yml
    strategy:
      fail-fast: true
      matrix:
        os: [linux]
    with:
      ccache_enabled: false
      os: ${{ matrix.os }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  package:
    if: ${{ github.repository_owner == 'XRPLF' }}
    needs: build-test
    uses: ./.github/workflows/reusable-package.yml
    with:
      publish: true
    secrets:
      remote_username: ${{ secrets.NEXUS_REMOTE_USERNAME }}
      remote_password: ${{ secrets.NEXUS_REMOTE_PASSWORD }}
      signing_key: ${{ secrets.NEXUS_PACKAGES_PRIVATE_KEY }}
