# This workflow uploads the libxrpl recipe to the Conan remote and builds
# release packages when a versioned tag is pushed.
name: Tag

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  upload-recipe:
    if: ${{ github.repository == 'XRPLF/rippled' }}
    uses: ./.github/workflows/reusable-upload-recipe.yml
    secrets:
      remote_username: ${{ secrets.CONAN_REMOTE_USERNAME }}
      remote_password: ${{ secrets.CONAN_REMOTE_PASSWORD }}

  build-test:
    if: ${{ github.repository == 'XRPLF/rippled' }}
    uses: ./.github/workflows/reusable-build-test.yml
    strategy:
      fail-fast: true
      matrix:
        os: [linux]
    with:
      ccache_enabled: false
      os: ${{ matrix.os }}
      strategy_matrix: minimal
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  package:
    if: ${{ github.repository == 'XRPLF/rippled' }}
    needs: build-test
    uses: ./.github/workflows/reusable-package.yml
