name: Determine PR number on push

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR number
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "Determining PR number from the ref name '${{ github.ref_name }}.'"

          if [[ '${{ github.ref_name }}' =~ ^refs/pull/([0-9]+)/merge$ ]]; then
            echo "PR number: ${BASH_REMATCH[1]}."
          else
            echo "Could not extract PR number."
          fi
          
          echo "$GITHUB_CONTEXT"
