name: Run pre-commit hooks

on:
  pull_request:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  run-hooks:
    uses: XRPLF/actions/.github/workflows/pre-commit.yml@af1b0f0d764cda2e5435f5ac97b240d4bd4d95d3
    with:
      runs_on: ubuntu-latest
      container: '{ "image": "ghcr.io/xrplf/ci/tools-rippled-pre-commit" }'
