# This workflow builds the documentation for the repository, and publishes it to
# GitHub Pages when changes are merged into the default branch.
name: Build and publish documentation

on:
  push:
    branches:
      - "develop"
    paths:
      - ".github/workflows/publish-docs.yml"
      - "*.md"
      - "**/*.md"
      - "docs/**"
      - "include/**"
      - "src/libxrpl/**"
      - "src/xrpld/**"
  pull_request:
    paths:
      - ".github/workflows/publish-docs.yml"
      - "*.md"
      - "**/*.md"
      - "docs/**"
      - "include/**"
      - "src/libxrpl/**"
      - "src/xrpld/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  BUILD_DIR: build
  # ubuntu-latest has only 2 CPUs for private repositories
  # https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for--private-repositories
  NPROC_SUBTRACT: ${{ github.event.repository.visibility == 'public' && '2' || '1' }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/xrplf/xrpld/nix-ubuntu:sha-fe4c8ae
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Prepare runner
        uses: XRPLF/actions/prepare-runner@c47daebb2f9db64ffbac71b47d68a661498d5ce8
        with:
          enable_ccache: false

      - name: Get number of processors
        uses: XRPLF/actions/get-nproc@cf0433aa74563aead044a1e395610c96d65a37cf
        id: nproc
        with:
          subtract: ${{ env.NPROC_SUBTRACT }}

      - name: Print build environment
        uses: XRPLF/actions/print-build-env@59dec886e4afb05a1724443af08baccbc045b574

      - name: Check Doxygen version
        run: doxygen --version

      - name: Build documentation
        env:
          BUILD_NPROC: ${{ steps.nproc.outputs.nproc }}
        run: |
          mkdir -p "${BUILD_DIR}"
          cd "${BUILD_DIR}"
          cmake -Donly_docs=ON ..
          cmake --build . --target docs --parallel ${BUILD_NPROC}

      - name: Create documentation artifact
        if: ${{ github.event.repository.visibility == 'public' && github.event_name == 'push' }}
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ${{ env.BUILD_DIR }}/docs/html

  deploy:
    if: ${{ github.repository == 'XRPLF/rippled' && github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5.0.0
