# Build the Conan package and run the consumer test package.
name: Test Conan package

# This workflow can only be triggered by other workflows.
on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  test-conan-package:
    runs-on: ubuntu-latest
    container: ghcr.io/xrplf/xrpld/nix-ubuntu:sha-63ffdc3
    timeout-minutes: 90

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Conan
        uses: ./.github/actions/setup-conan

      - name: Export Conan package under test
        run: conan export . --version=head

      - name: Run Conan package test
        working-directory: tests/conan
        run: |
          conan test . xrpl/head \
              --profile:all ci \
              --build=missing \
              --settings:all build_type=Release \
              --conf:all tools.build:jobs="$(nproc)"
