name: Build and test configuration

on:
  workflow_call:
    inputs:
      build_only:
        description: 'Whether to only build or to build and test the code ("true", "false").'
        required: true
        type: boolean

      build_type:
        description: 'The build type to use ("Debug", "Release").'
        required: true
        type: string

      ccache_enabled:
        description: "Whether to enable ccache."
        required: false
        type: boolean
        default: false

      cmake_args:
        description: "Additional arguments to pass to CMake."
        required: false
        type: string
        default: ""

      cmake_target:
        description: "The CMake target to build."
        required: true
        type: string

      runs_on:
        description: Runner to run the job on as a JSON string
        required: true
        type: string

      image:
        description: "The image to run in (leave empty to run natively)"
        required: true
        type: string

      config_name:
        description: "The configuration string (used for naming artifacts and such)."
        required: true
        type: string

      nproc_subtract:
        description: "The number of processors to subtract when calculating parallelism."
        required: false
        type: number
        default: 2

      sanitizers:
        description: "The sanitizers to enable."
        required: false
        type: string
        default: ""

    secrets:
      CODECOV_TOKEN:
        description: "The Codecov token to use for uploading coverage reports."
        required: true

defaults:
  run:
    shell: bash

env:
  # Conan installs the generators in the build/generators directory, see the
  # layout() method in conanfile.py. We then run CMake from the build directory.
  BUILD_DIR: build

jobs:
  build-and-test:
    name: ${{ inputs.config_name }}
    runs-on: ${{ fromJSON(inputs.runs_on) }}
    container: ${{ inputs.image != '' && inputs.image || null }}
    timeout-minutes: 60
    env:
      # Use a namespace to keep the objects separate for each configuration.
      CCACHE_NAMESPACE: ${{ inputs.config_name }}
      # Ccache supports both Redis and HTTP endpoints.
      # * For Redis, use the following format: redis://ip:port, see
      #   https://github.com/ccache/ccache/wiki/Redis-storage. Note that TLS is
      #   not directly supported by ccache, and requires use of a proxy.
      # * For HTTP use the following format: http://ip:port/cache when using
      #   nginx as backend or http://ip:port|layout=bazel when using Bazel
      #   Remote Cache, see https://github.com/ccache/ccache/wiki/HTTP-storage.
      #   Note that HTTPS is not directly supported by ccache.
      CCACHE_REMOTE_ONLY: true
      CCACHE_REMOTE_STORAGE: http://cache.dev.ripplex.io:8080|layout=bazel
      # Ignore the creation and modification timestamps on files, since the
      # header files are copied into separate directories by CMake, which will
      # otherwise result in cache misses.
      CCACHE_SLOPPINESS: include_file_ctime,include_file_mtime
      # Determine if coverage and voidstar should be enabled.
      COVERAGE_ENABLED: ${{ contains(inputs.cmake_args, '-Dcoverage=ON') }}
      VOIDSTAR_ENABLED: ${{ contains(inputs.cmake_args, '-Dvoidstar=ON') }}
      SANITIZERS_ENABLED: ${{ inputs.sanitizers != '' }}
    steps:
      - name: Cleanup workspace (macOS and Windows)
        if: ${{ runner.os == 'macOS' || runner.os == 'Windows' }}
        uses: XRPLF/actions/cleanup-workspace@cf0433aa74563aead044a1e395610c96d65a37cf

      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Prepare runner
        uses: XRPLF/actions/prepare-runner@2cbf481018d930656e9276fcc20dc0e3a0be5b6d
        with:
          enable_ccache: ${{ inputs.ccache_enabled }}

      - name: Set ccache log file
        if: ${{ inputs.ccache_enabled && runner.debug == '1' }}
        run: echo "CCACHE_LOGFILE=${{ runner.temp }}/ccache.log" >> "${GITHUB_ENV}"

      - name: Print build environment
        uses: ./.github/actions/print-env

      - name: Get number of processors
        uses: XRPLF/actions/get-nproc@cf0433aa74563aead044a1e395610c96d65a37cf
        id: nproc
        with:
          subtract: ${{ inputs.nproc_subtract }}

      - name: Setup Conan
        env:
          SANITIZERS: ${{ inputs.sanitizers }}
        uses: ./.github/actions/setup-conan

      - name: Build dependencies
        uses: ./.github/actions/build-deps
        with:
          build_nproc: ${{ steps.nproc.outputs.nproc }}
          build_type: ${{ inputs.build_type }}
          # Set the verbosity to "quiet" for Windows to avoid an excessive
          # amount of logs. For other OSes, the "verbose" logs are more useful.
          log_verbosity: ${{ runner.os == 'Windows' && 'quiet' || 'verbose' }}
          sanitizers: ${{ inputs.sanitizers }}

      - name: Configure CMake
        working-directory: ${{ env.BUILD_DIR }}
        env:
          BUILD_TYPE: ${{ inputs.build_type }}
          SANITIZERS: ${{ inputs.sanitizers }}
          CMAKE_ARGS: ${{ inputs.cmake_args }}
        run: |
          cmake \
            -G '${{ runner.os == 'Windows' && 'Visual Studio 17 2022' || 'Ninja' }}' \
            -DCMAKE_TOOLCHAIN_FILE:FILEPATH=build/generators/conan_toolchain.cmake \
            -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
            ${CMAKE_ARGS} \
            ..

      - name: Build the binary
        working-directory: ${{ env.BUILD_DIR }}
        env:
          BUILD_NPROC: ${{ steps.nproc.outputs.nproc }}
          BUILD_TYPE: ${{ inputs.build_type }}
          CMAKE_TARGET: ${{ inputs.cmake_target }}
        run: |
          cmake \
            --build . \
            --config "${BUILD_TYPE}" \
            --parallel "${BUILD_NPROC}" \
            --target "${CMAKE_TARGET}"

      - name: Show ccache statistics
        if: ${{ inputs.ccache_enabled }}
        run: |
          ccache --show-stats -vv
          if [ '${{ runner.debug }}' = '1' ]; then
            cat "${CCACHE_LOGFILE}"
            curl ${CCACHE_REMOTE_STORAGE%|*}/status || true
          fi

      - name: Upload the binary (Linux)
        if: ${{ github.repository_owner == 'XRPLF' && runner.os == 'Linux' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: xrpld-${{ inputs.config_name }}
          path: ${{ env.BUILD_DIR }}/xrpld
          retention-days: 3
          if-no-files-found: error

      - name: Check linking (Linux)
        if: ${{ runner.os == 'Linux' && env.SANITIZERS_ENABLED == 'false' }}
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          ldd ./xrpld
          if [ "$(ldd ./xrpld | grep -E '(libstdc\+\+|libgcc)' | wc -l)" -eq 0 ]; then
            echo 'The binary is statically linked.'
          else
            echo 'The binary is dynamically linked.'
            exit 1
          fi

      - name: Verify presence of instrumentation (Linux)
        if: ${{ runner.os == 'Linux' && env.VOIDSTAR_ENABLED == 'true' }}
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          ./xrpld --version | grep libvoidstar

      - name: Set sanitizer options
        if: ${{ !inputs.build_only && env.SANITIZERS_ENABLED == 'true' }}
        run: |
          echo "ASAN_OPTIONS=print_stacktrace=1:detect_container_overflow=0:suppressions=${GITHUB_WORKSPACE}/sanitizers/suppressions/asan.supp" >> ${GITHUB_ENV}
          echo "TSAN_OPTIONS=second_deadlock_stack=1:halt_on_error=0:suppressions=${GITHUB_WORKSPACE}/sanitizers/suppressions/tsan.supp" >> ${GITHUB_ENV}
          echo "UBSAN_OPTIONS=suppressions=${GITHUB_WORKSPACE}/sanitizers/suppressions/ubsan.supp" >> ${GITHUB_ENV}
          echo "LSAN_OPTIONS=suppressions=${GITHUB_WORKSPACE}/sanitizers/suppressions/lsan.supp" >> ${GITHUB_ENV}

      - name: Run the separate tests
        if: ${{ !inputs.build_only }}
        working-directory: ${{ env.BUILD_DIR }}
        # Windows locks some of the build files while running tests, and parallel jobs can collide
        env:
          BUILD_TYPE: ${{ inputs.build_type }}
          PARALLELISM: ${{ runner.os == 'Windows' && '1' || steps.nproc.outputs.nproc }}
        run: |
          ctest \
            --output-on-failure \
            -C "${BUILD_TYPE}" \
            -j "${PARALLELISM}"

      - name: Run the embedded tests
        if: ${{ !inputs.build_only }}
        working-directory: ${{ runner.os == 'Windows' && format('{0}/{1}', env.BUILD_DIR, inputs.build_type) || env.BUILD_DIR }}
        env:
          BUILD_NPROC: ${{ steps.nproc.outputs.nproc }}
        run: |
          ./xrpld --unittest --unittest-jobs "${BUILD_NPROC}"

      - name: Debug failure (Linux)
        if: ${{ failure() && runner.os == 'Linux' && !inputs.build_only }}
        run: |
          echo "IPv4 local port range:"
          cat /proc/sys/net/ipv4/ip_local_port_range
          echo "Netstat:"
          netstat -an

      - name: Prepare coverage report
        if: ${{ !inputs.build_only && env.COVERAGE_ENABLED == 'true' }}
        working-directory: ${{ env.BUILD_DIR }}
        env:
          BUILD_NPROC: ${{ steps.nproc.outputs.nproc }}
          BUILD_TYPE: ${{ inputs.build_type }}
        run: |
          cmake \
            --build . \
            --config "${BUILD_TYPE}" \
            --parallel "${BUILD_NPROC}" \
            --target coverage

      - name: Upload coverage report
        if: ${{ github.repository_owner == 'XRPLF' && !inputs.build_only && env.COVERAGE_ENABLED == 'true' }}
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          disable_search: true
          disable_telem: true
          fail_ci_if_error: true
          files: ${{ env.BUILD_DIR }}/coverage.xml
          plugins: noop
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
