name: Check runner's Docker version
on:
  push:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        ro: [heavy, x-heavy, heavy-arm64, x-heavy-arm64]
        # num: [1, 2, 3, 4, 5]
    runs-on: ${{ matrix.ro }}
    name: ${{ matrix.ro }} check
    # name: ${{ matrix.ro }} check ${{ matrix.num }}
    # container: ghcr.io/xrplf/ci/ubuntu-jammy:gcc12
    container: gcc:12

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check environment
        run: |
          printenv
          set -x
          . /etc/os-release
          echo "nproc: $(cat /proc/cpuinfo | grep processor | tail -n1)" | tee -a $GITHUB_STEP_SUMMARY
          echo "mem: $(free -m)" | tee -a $GITHUB_STEP_SUMMARY
          echo "Arch: $(uname -m)" | tee -a $GITHUB_STEP_SUMMARY
          echo "Version: $VERSION" | tee -a $GITHUB_STEP_SUMMARY
          echo "Docker engine: $(docker --version)" | tee -a $GITHUB_STEP_SUMMARY
          echo "test"
          for plugin in compose buildx; do
            if output=$(docker ${plugin} version 2>&1); then
              echo "${plugin} version: $output" | tee -a "$GITHUB_STEP_SUMMARY"
            else
              echo "Docker ${plugin} not installed: $output" | tee -a "$GITHUB_STEP_SUMMARY"
            fi
          done
