name: Check runners
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependencies:
    strategy:
      matrix:
        ro: [heavy, x-heavy]
        arch: ["x86_64", "ARM64"]
        num: [1, 2]
    runs-on: ${{ matrix.ro }}
    # container: ghcr.io/xrplf/rippled-build-ubuntu:aaf5e3e

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check environment
        run: |
          set -x
          docker --version | tee -a $GITHUB_STEP_SUMMARY
          docker compose version || true | tee -a $GITHUB_STEP_SUMMARY
          docker buildx version || true | tee -a $GITHUB_STEP_SUMMARY
