

name: test
on: [push, pull_request]
jobs:

  test:
    strategy:
      matrix:
        include:
          - site: "production"
            datacenter: "site-a"
          - site: "staging"
            datacenter: "site-b"
    runs-on: x-heavy
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install Ninja on Linux
        run: |
          sleep 301
          echo "done"
